-- Carga assistida de impressoras informada em 10/09/2026.
-- Executar no SQL Editor do Lovable.
-- USB LOCAL e RESERVA ficam sem IP, mas permanecem como registros editáveis.
begin;

insert into public.controle_ip (unidade,categoria,ip,nome,local,setor,andar,modelo,fabricante,patrimonio,observacoes) values ('MATRIZ','impressoras','192.168.0.34'::inet,'Impressora Qualidade','QUALIDADE','QUALIDADE','4° ANDAR','Canon IR 1643iF','Canon','2TQ14788',null) on conflict (ip) where ip is not null do update set unidade=excluded.unidade,categoria=excluded.categoria,nome=excluded.nome,local=excluded.local,setor=excluded.setor,andar=excluded.andar,modelo=excluded.modelo,fabricante=excluded.fabricante,patrimonio=excluded.patrimonio,observacoes=excluded.observacoes,atualizado_em=now();
insert into public.controle_ip (unidade,categoria,nome,local,setor,andar,modelo,fabricante,patrimonio,observacoes) values ('MATRIZ','impressoras','Impressora Fotos Qualidade','FOTOS QUALIDADE','FOTOS QUALIDADE','4° ANDAR',null,null,'AK61009505','Sem IP informado; inventário indica equipamento local') ;
insert into public.controle_ip (unidade,categoria,ip,nome,local,setor,andar,modelo,fabricante,patrimonio,observacoes) values ('MATRIZ','impressoras','192.168.0.6'::inet,'Impressora RH-DP','RH-DP','RH-DP','4° ANDAR','Canon IR 1643iF','Canon','2TQ14939',null) on conflict (ip) where ip is not null do update set unidade=excluded.unidade,categoria=excluded.categoria,nome=excluded.nome,local=excluded.local,setor=excluded.setor,andar=excluded.andar,modelo=excluded.modelo,fabricante=excluded.fabricante,patrimonio=excluded.patrimonio,observacoes=excluded.observacoes,atualizado_em=now();
insert into public.controle_ip (unidade,categoria,ip,nome,local,setor,andar,modelo,fabricante,patrimonio,observacoes) values ('MATRIZ','impressoras','192.168.0.65'::inet,'Impressora Marcação','MARCAÇÃO','MARCAÇÃO','4° ANDAR','Canon IR 1643iF','Canon','2TQ14683',null) on conflict (ip) where ip is not null do update set unidade=excluded.unidade,categoria=excluded.categoria,nome=excluded.nome,local=excluded.local,setor=excluded.setor,andar=excluded.andar,modelo=excluded.modelo,fabricante=excluded.fabricante,patrimonio=excluded.patrimonio,observacoes=excluded.observacoes,atualizado_em=now();
insert into public.controle_ip (unidade,categoria,ip,nome,local,setor,andar,modelo,fabricante,patrimonio,observacoes) values ('MATRIZ','impressoras','192.168.0.54'::inet,'Impressora Faturamento','FATURAMENTO','FATURAMENTO','4° ANDAR','Canon IR 1643iF','Canon','2TQ07841',null) on conflict (ip) where ip is not null do update set unidade=excluded.unidade,categoria=excluded.categoria,nome=excluded.nome,local=excluded.local,setor=excluded.setor,andar=excluded.andar,modelo=excluded.modelo,fabricante=excluded.fabricante,patrimonio=excluded.patrimonio,observacoes=excluded.observacoes,atualizado_em=now();
insert into public.controle_ip (unidade,categoria,ip,nome,local,setor,andar,modelo,fabricante,patrimonio,observacoes) values ('MATRIZ','impressoras','192.168.0.20'::inet,'Impressora Financeiro','FINANCEIRO','FINANCEIRO','4° ANDAR','Canon IR 1643iF','Canon','2TQ14997',null) on conflict (ip) where ip is not null do update set unidade=excluded.unidade,categoria=excluded.categoria,nome=excluded.nome,local=excluded.local,setor=excluded.setor,andar=excluded.andar,modelo=excluded.modelo,fabricante=excluded.fabricante,patrimonio=excluded.patrimonio,observacoes=excluded.observacoes,atualizado_em=now();

insert into public.controle_ip (unidade,categoria,ip,nome,local,setor,andar,modelo,fabricante,patrimonio,observacoes) values ('MATRIZ','impressoras','192.168.0.7'::inet,'Impressora Recepção ECO','RECEPÇÃO ECO','RECEPÇÃO ECO','3° ANDAR','Canon IR 1643iF','Canon','2TQ14732',null) on conflict (ip) where ip is not null do update set unidade=excluded.unidade,categoria=excluded.categoria,nome=excluded.nome,local=excluded.local,setor=excluded.setor,andar=excluded.andar,modelo=excluded.modelo,fabricante=excluded.fabricante,patrimonio=excluded.patrimonio,observacoes=excluded.observacoes,atualizado_em=now();
insert into public.controle_ip (unidade,categoria,ip,nome,local,setor,andar,modelo,fabricante,patrimonio,observacoes) values ('MATRIZ','impressoras','192.168.0.122'::inet,'Impressora Fotos ECO','FOTOS ECO','FOTOS ECO','3° ANDAR','XEROX C7020','XEROX','7TX144871',null) on conflict (ip) where ip is not null do update set unidade=excluded.unidade,categoria=excluded.categoria,nome=excluded.nome,local=excluded.local,setor=excluded.setor,andar=excluded.andar,modelo=excluded.modelo,fabricante=excluded.fabricante,patrimonio=excluded.patrimonio,observacoes=excluded.observacoes,atualizado_em=now();
insert into public.controle_ip (unidade,categoria,nome,local,setor,andar,modelo,fabricante,patrimonio,observacoes) values ('MATRIZ','impressoras','Impressora Administração','ADMINISTRAÇÃO','ADMINISTRAÇÃO','3° ANDAR','Pantum','Pantum','CK3B004479','USB LOCAL') ;
insert into public.controle_ip (unidade,categoria,nome,local,setor,andar,modelo,fabricante,patrimonio,observacoes) values ('MATRIZ','impressoras','Impressora Compras','COMPRAS','COMPRAS','3° ANDAR','HP','HP','PROPRIA','USB LOCAL') ;

insert into public.controle_ip (unidade,categoria,ip,nome,local,setor,andar,modelo,fabricante,patrimonio,observacoes) values ('MATRIZ','impressoras','192.168.0.22'::inet,'Impressora Informática','INFORMATICA','INFORMATICA','2° ANDAR','Canon IR 1643iF','Canon','2TQ14937',null) on conflict (ip) where ip is not null do update set unidade=excluded.unidade,categoria=excluded.categoria,nome=excluded.nome,local=excluded.local,setor=excluded.setor,andar=excluded.andar,modelo=excluded.modelo,fabricante=excluded.fabricante,patrimonio=excluded.patrimonio,observacoes=excluded.observacoes,atualizado_em=now();
insert into public.controle_ip (unidade,categoria,ip,nome,local,setor,andar,modelo,fabricante,patrimonio,observacoes) values ('MATRIZ','impressoras','192.168.0.14'::inet,'Impressora Sala 7','SALA 7','SALA 7','2° ANDAR','Brother HL-6402DW','Brother','U64187K6N419392',null) on conflict (ip) where ip is not null do update set unidade=excluded.unidade,categoria=excluded.categoria,nome=excluded.nome,local=excluded.local,setor=excluded.setor,andar=excluded.andar,modelo=excluded.modelo,fabricante=excluded.fabricante,patrimonio=excluded.patrimonio,observacoes=excluded.observacoes,atualizado_em=now();
insert into public.controle_ip (unidade,categoria,ip,nome,local,setor,andar,modelo,fabricante,patrimonio,observacoes) values ('MATRIZ','impressoras','192.168.0.3'::inet,'Impressora Recepção','RECEPÇÃO','RECEPÇÃO','2° ANDAR','Brother HL-6402DW','Brother','2TQ14672',null) on conflict (ip) where ip is not null do update set unidade=excluded.unidade,categoria=excluded.categoria,nome=excluded.nome,local=excluded.local,setor=excluded.setor,andar=excluded.andar,modelo=excluded.modelo,fabricante=excluded.fabricante,patrimonio=excluded.patrimonio,observacoes=excluded.observacoes,atualizado_em=now();

insert into public.controle_ip (unidade,categoria,ip,nome,local,setor,andar,modelo,fabricante,patrimonio,observacoes) values ('MATRIZ','impressoras','192.168.0.90'::inet,'Impressora Fotos Principal','FOTOS PRINCIPAL','FOTOS PRINCIPAL','1° ANDAR','KONICA C454e','KONICA','A5C0011023297',null) on conflict (ip) where ip is not null do update set unidade=excluded.unidade,categoria=excluded.categoria,nome=excluded.nome,local=excluded.local,setor=excluded.setor,andar=excluded.andar,modelo=excluded.modelo,fabricante=excluded.fabricante,patrimonio=excluded.patrimonio,observacoes=excluded.observacoes,atualizado_em=now();
insert into public.controle_ip (unidade,categoria,ip,nome,local,setor,andar,modelo,fabricante,patrimonio,observacoes) values ('MATRIZ','impressoras','192.168.0.4'::inet,'Impressora Impressão','IMPRESSÃO','IMPRESSÃO','1° ANDAR','Brother HL-6402DW','Brother','U64187K6N419388',null) on conflict (ip) where ip is not null do update set unidade=excluded.unidade,categoria=excluded.categoria,nome=excluded.nome,local=excluded.local,setor=excluded.setor,andar=excluded.andar,modelo=excluded.modelo,fabricante=excluded.fabricante,patrimonio=excluded.patrimonio,observacoes=excluded.observacoes,atualizado_em=now();
insert into public.controle_ip (unidade,categoria,nome,local,setor,andar,modelo,fabricante,patrimonio,observacoes) values ('MATRIZ','impressoras','Impressora Sala 3','SALA 3','SALA 3','1° ANDAR','Brother HL-6402DW','Brother','U64187K6N419903','USB LOCAL');
insert into public.controle_ip (unidade,categoria,nome,local,setor,andar,modelo,fabricante,patrimonio,observacoes) values ('MATRIZ','impressoras','Impressora Sala 4','SALA 4','SALA 4','1° ANDAR','Pantum','Pantum','CL5W000236','USB LOCAL');
insert into public.controle_ip (unidade,categoria,nome,local,setor,andar,modelo,fabricante,patrimonio,observacoes) values ('MATRIZ','impressoras','Impressora Sala 5','SALA 5','SALA 5','1° ANDAR','Brother HL-6402DW','Brother','U64187K6N419923','USB LOCAL');
insert into public.controle_ip (unidade,categoria,ip,nome,local,setor,andar,modelo,fabricante,patrimonio,observacoes) values ('MATRIZ','impressoras','192.168.0.9'::inet,'Impressora Recepção 2','RECEPÇÃO 2','RECEPÇÃO 2','1° ANDAR','Canon IR 1643iF','Canon','2TQ14992',null) on conflict (ip) where ip is not null do update set unidade=excluded.unidade,categoria=excluded.categoria,nome=excluded.nome,local=excluded.local,setor=excluded.setor,andar=excluded.andar,modelo=excluded.modelo,fabricante=excluded.fabricante,patrimonio=excluded.patrimonio,observacoes=excluded.observacoes,atualizado_em=now();
insert into public.controle_ip (unidade,categoria,ip,nome,local,setor,andar,modelo,fabricante,patrimonio,observacoes) values ('MATRIZ','impressoras','192.168.0.38'::inet,'Impressora Recepção 1','RECEPÇÃO 1','RECEPÇÃO 1','1° ANDAR','Canon IR 1643iF','Canon','2TQ14730',null) on conflict (ip) where ip is not null do update set unidade=excluded.unidade,categoria=excluded.categoria,nome=excluded.nome,local=excluded.local,setor=excluded.setor,andar=excluded.andar,modelo=excluded.modelo,fabricante=excluded.fabricante,patrimonio=excluded.patrimonio,observacoes=excluded.observacoes,atualizado_em=now();

insert into public.controle_ip (unidade,categoria,ip,nome,local,setor,andar,modelo,fabricante,patrimonio,observacoes) values ('MATRIZ','impressoras','192.168.0.114'::inet,'Impressora Fotos','FOTOS','FOTOS','SUB SOLO','XEROX C7020','XEROX','3UA292527',null) on conflict (ip) where ip is not null do update set unidade=excluded.unidade,categoria=excluded.categoria,nome=excluded.nome,local=excluded.local,setor=excluded.setor,andar=excluded.andar,modelo=excluded.modelo,fabricante=excluded.fabricante,patrimonio=excluded.patrimonio,observacoes=excluded.observacoes,atualizado_em=now();
insert into public.controle_ip (unidade,categoria,ip,nome,local,setor,andar,modelo,fabricante,patrimonio,observacoes) values ('MATRIZ','impressoras','192.168.0.80'::inet,'Impressora Mamografia Filme','MAMOGRAFIA FILME','MAMOGRAFIA FILME','MAMOGRAFIA','HOLOGIC (IMEX)','HOLOGIC (IMEX)',null,null) on conflict (ip) where ip is not null do update set unidade=excluded.unidade,categoria=excluded.categoria,nome=excluded.nome,local=excluded.local,setor=excluded.setor,andar=excluded.andar,modelo=excluded.modelo,fabricante=excluded.fabricante,patrimonio=excluded.patrimonio,observacoes=excluded.observacoes,atualizado_em=now();
insert into public.controle_ip (unidade,categoria,ip,nome,local,setor,andar,modelo,fabricante,patrimonio,observacoes) values ('MATRIZ','impressoras','192.168.0.45'::inet,'Impressora Mamografia Laudo','MAMOGRAFIA LAUDO','MAMOGRAFIA LAUDO','MAMOGRAFIA','Canon IR 1643iF','Canon','2TQ14773',null) on conflict (ip) where ip is not null do update set unidade=excluded.unidade,categoria=excluded.categoria,nome=excluded.nome,local=excluded.local,setor=excluded.setor,andar=excluded.andar,modelo=excluded.modelo,fabricante=excluded.fabricante,patrimonio=excluded.patrimonio,observacoes=excluded.observacoes,atualizado_em=now();
insert into public.controle_ip (unidade,categoria,ip,nome,local,setor,andar,modelo,fabricante,patrimonio,observacoes) values ('MATRIZ','impressoras','192.168.0.13'::inet,'Impressora Recepção Mamografia','RECEPÇÃO','RECEPÇÃO','MAMOGRAFIA','Canon IR 1643iF','Canon','2TQ14589',null) on conflict (ip) where ip is not null do update set unidade=excluded.unidade,categoria=excluded.categoria,nome=excluded.nome,local=excluded.local,setor=excluded.setor,andar=excluded.andar,modelo=excluded.modelo,fabricante=excluded.fabricante,patrimonio=excluded.patrimonio,observacoes=excluded.observacoes,atualizado_em=now();

insert into public.controle_ip (unidade,categoria,ip,nome,local,setor,andar,modelo,fabricante,patrimonio,observacoes) values ('MN','impressoras','192.168.1.7'::inet,'Impressora Recepção MN','RECEPÇÃO','RECEPÇÃO','TÉRREO','Canon IR 1643iF','Canon','2TQ14673',null) on conflict (ip) where ip is not null do update set unidade=excluded.unidade,categoria=excluded.categoria,nome=excluded.nome,local=excluded.local,setor=excluded.setor,andar=excluded.andar,modelo=excluded.modelo,fabricante=excluded.fabricante,patrimonio=excluded.patrimonio,observacoes=excluded.observacoes,atualizado_em=now();
insert into public.controle_ip (unidade,categoria,ip,nome,local,setor,andar,modelo,fabricante,patrimonio,observacoes) values ('MN','impressoras','192.168.1.10'::inet,'Impressora Sala de Laudos','SALA DE LAUDOS (DR.MARCELO)','SALA DE LAUDOS (DR.MARCELO)','TÉRREO','Brother HL-6402DW','Brother','U64187K6N419312',null) on conflict (ip) where ip is not null do update set unidade=excluded.unidade,categoria=excluded.categoria,nome=excluded.nome,local=excluded.local,setor=excluded.setor,andar=excluded.andar,modelo=excluded.modelo,fabricante=excluded.fabricante,patrimonio=excluded.patrimonio,observacoes=excluded.observacoes,atualizado_em=now();
insert into public.controle_ip (unidade,categoria,nome,local,setor,andar,modelo,fabricante,patrimonio,observacoes) values ('MN','impressoras','Impressora Teste Ergométrico Térreo','TESTE ERGOMETRICO TÉRREO','TESTE ERGOMETRICO TÉRREO','TÉRREO','Brother HL-6402DW','Brother','U64187D6N249650','USB LOCAL');
insert into public.controle_ip (unidade,categoria,ip,nome,local,setor,andar,modelo,fabricante,patrimonio,observacoes) values ('MN','impressoras','192.168.1.223'::inet,'Impressora Fotos MN','FOTOS','FOTOS','TÉRREO','KONICA C284e','KONICA','A5C2011106995',null) on conflict (ip) where ip is not null do update set unidade=excluded.unidade,categoria=excluded.categoria,nome=excluded.nome,local=excluded.local,setor=excluded.setor,andar=excluded.andar,modelo=excluded.modelo,fabricante=excluded.fabricante,patrimonio=excluded.patrimonio,observacoes=excluded.observacoes,atualizado_em=now();
insert into public.controle_ip (unidade,categoria,ip,nome,local,setor,andar,modelo,fabricante,patrimonio,observacoes) values ('MN','impressoras','192.168.1.6'::inet,'Impressora Laudos Subsolo MN','LAUDOS SUBSOLO MN','LAUDOS SUBSOLO MN','SUB SOLO','Pantum','Pantum','CL5W001250',null) on conflict (ip) where ip is not null do update set unidade=excluded.unidade,categoria=excluded.categoria,nome=excluded.nome,local=excluded.local,setor=excluded.setor,andar=excluded.andar,modelo=excluded.modelo,fabricante=excluded.fabricante,patrimonio=excluded.patrimonio,observacoes=excluded.observacoes,atualizado_em=now();
insert into public.controle_ip (unidade,categoria,nome,local,setor,andar,modelo,fabricante,patrimonio,observacoes) values ('MN','impressoras','Impressora Teste Ergométrico Subsolo','TESTE ERGOMETRICO SUBSOLO','TESTE ERGOMETRICO SUBSOLO','SUB SOLO','Brother HL-6402DW','Brother','U64187K6N419286','USB LOCAL');
insert into public.controle_ip (unidade,categoria,nome,local,setor,modelo,fabricante,patrimonio,observacoes) values ('MN','impressoras','Impressora Reserva MN','RESERVA MN','RESERVA MN','Brother HL-6402DW','Brother','U64187K6N419935','RESERVA; sem IP informado');
insert into public.controle_ip (unidade,categoria,nome,local,setor,modelo,fabricante,patrimonio,observacoes) values ('MATRIZ','impressoras','Impressora Reserva Matriz','RESERVA MATRIZ','RESERVA MATRIZ','Canon IR 1643iF','Canon','2TQ14805','RESERVA; sem IP informado');

insert into public.audit_logs (tabela,operacao,observacoes,dados_novos) values ('controle_ip','IMPORT','Carga assistida de impressoras; USB LOCAL e reservas preservados sem IP.',jsonb_build_object('categoria','impressoras','registros',32,'ips',22,'sem_ip',10));
commit;
