/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedColaboradorasRouteImport } from './routes/_authenticated/colaboradoras'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEnfermagemRouteImport } from './routes/_authenticated/enfermagem'
import { Route as AuthenticatedEscalaRouteImport } from './routes/_authenticated/escala'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedItensRouteImport } from './routes/_authenticated/itens'
import { Route as AuthenticatedMedicosRouteImport } from './routes/_authenticated/medicos'
import { Route as AuthenticatedNotasRouteImport } from './routes/_authenticated/notas'
import { Route as AuthenticatedPacientesRouteImport } from './routes/_authenticated/pacientes'
import { Route as AuthenticatedRamaisRouteImport } from './routes/_authenticated/ramais'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedSalasRouteImport } from './routes/_authenticated/salas'
import { Route as AuthenticatedSenhasRouteImport } from './routes/_authenticated/senhas'
import { Route as AuthenticatedSobreRouteImport } from './routes/_authenticated/sobre'
import { Route as AuthenticatedSolicitacoesRouteImport } from './routes/_authenticated/solicitacoes'
import { Route as AuthenticatedSondasRouteImport } from './routes/_authenticated/sondas'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedColaboradorasRoute =
  AuthenticatedColaboradorasRouteImport.update({
    id: '/colaboradoras',
    path: '/colaboradoras',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEnfermagemRoute = AuthenticatedEnfermagemRouteImport.update({
  id: '/enfermagem',
  path: '/enfermagem',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEscalaRoute = AuthenticatedEscalaRouteImport.update({
  id: '/escala',
  path: '/escala',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedItensRoute = AuthenticatedItensRouteImport.update({
  id: '/itens',
  path: '/itens',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMedicosRoute = AuthenticatedMedicosRouteImport.update({
  id: '/medicos',
  path: '/medicos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotasRoute = AuthenticatedNotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPacientesRoute = AuthenticatedPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRamaisRoute = AuthenticatedRamaisRouteImport.update({
  id: '/ramais',
  path: '/ramais',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalasRoute = AuthenticatedSalasRouteImport.update({
  id: '/salas',
  path: '/salas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSenhasRoute = AuthenticatedSenhasRouteImport.update({
  id: '/senhas',
  path: '/senhas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSobreRoute = AuthenticatedSobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSolicitacoesRoute =
  AuthenticatedSolicitacoesRouteImport.update({
    id: '/solicitacoes',
    path: '/solicitacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSondasRoute = AuthenticatedSondasRouteImport.update({
  id: '/sondas',
  path: '/sondas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/colaboradoras': typeof AuthenticatedColaboradorasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/enfermagem': typeof AuthenticatedEnfermagemRoute
  '/escala': typeof AuthenticatedEscalaRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/itens': typeof AuthenticatedItensRoute
  '/medicos': typeof AuthenticatedMedicosRoute
  '/notas': typeof AuthenticatedNotasRoute
  '/pacientes': typeof AuthenticatedPacientesRoute
  '/ramais': typeof AuthenticatedRamaisRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/salas': typeof AuthenticatedSalasRoute
  '/senhas': typeof AuthenticatedSenhasRoute
  '/sobre': typeof AuthenticatedSobreRoute
  '/solicitacoes': typeof AuthenticatedSolicitacoesRoute
  '/sondas': typeof AuthenticatedSondasRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/colaboradoras': typeof AuthenticatedColaboradorasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/enfermagem': typeof AuthenticatedEnfermagemRoute
  '/escala': typeof AuthenticatedEscalaRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/itens': typeof AuthenticatedItensRoute
  '/medicos': typeof AuthenticatedMedicosRoute
  '/notas': typeof AuthenticatedNotasRoute
  '/pacientes': typeof AuthenticatedPacientesRoute
  '/ramais': typeof AuthenticatedRamaisRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/salas': typeof AuthenticatedSalasRoute
  '/senhas': typeof AuthenticatedSenhasRoute
  '/sobre': typeof AuthenticatedSobreRoute
  '/solicitacoes': typeof AuthenticatedSolicitacoesRoute
  '/sondas': typeof AuthenticatedSondasRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/colaboradoras': typeof AuthenticatedColaboradorasRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/enfermagem': typeof AuthenticatedEnfermagemRoute
  '/_authenticated/escala': typeof AuthenticatedEscalaRoute
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRoute
  '/_authenticated/itens': typeof AuthenticatedItensRoute
  '/_authenticated/medicos': typeof AuthenticatedMedicosRoute
  '/_authenticated/notas': typeof AuthenticatedNotasRoute
  '/_authenticated/pacientes': typeof AuthenticatedPacientesRoute
  '/_authenticated/ramais': typeof AuthenticatedRamaisRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/salas': typeof AuthenticatedSalasRoute
  '/_authenticated/senhas': typeof AuthenticatedSenhasRoute
  '/_authenticated/sobre': typeof AuthenticatedSobreRoute
  '/_authenticated/solicitacoes': typeof AuthenticatedSolicitacoesRoute
  '/_authenticated/sondas': typeof AuthenticatedSondasRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/colaboradoras'
    | '/dashboard'
    | '/enfermagem'
    | '/escala'
    | '/estoque'
    | '/itens'
    | '/medicos'
    | '/notas'
    | '/pacientes'
    | '/ramais'
    | '/relatorios'
    | '/salas'
    | '/senhas'
    | '/sobre'
    | '/solicitacoes'
    | '/sondas'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/colaboradoras'
    | '/dashboard'
    | '/enfermagem'
    | '/escala'
    | '/estoque'
    | '/itens'
    | '/medicos'
    | '/notas'
    | '/pacientes'
    | '/ramais'
    | '/relatorios'
    | '/salas'
    | '/senhas'
    | '/sobre'
    | '/solicitacoes'
    | '/sondas'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/colaboradoras'
    | '/_authenticated/dashboard'
    | '/_authenticated/enfermagem'
    | '/_authenticated/escala'
    | '/_authenticated/estoque'
    | '/_authenticated/itens'
    | '/_authenticated/medicos'
    | '/_authenticated/notas'
    | '/_authenticated/pacientes'
    | '/_authenticated/ramais'
    | '/_authenticated/relatorios'
    | '/_authenticated/salas'
    | '/_authenticated/senhas'
    | '/_authenticated/sobre'
    | '/_authenticated/solicitacoes'
    | '/_authenticated/sondas'
    | '/_authenticated/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/colaboradoras': {
      id: '/_authenticated/colaboradoras'
      path: '/colaboradoras'
      fullPath: '/colaboradoras'
      preLoaderRoute: typeof AuthenticatedColaboradorasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enfermagem': {
      id: '/_authenticated/enfermagem'
      path: '/enfermagem'
      fullPath: '/enfermagem'
      preLoaderRoute: typeof AuthenticatedEnfermagemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/escala': {
      id: '/_authenticated/escala'
      path: '/escala'
      fullPath: '/escala'
      preLoaderRoute: typeof AuthenticatedEscalaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/itens': {
      id: '/_authenticated/itens'
      path: '/itens'
      fullPath: '/itens'
      preLoaderRoute: typeof AuthenticatedItensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/medicos': {
      id: '/_authenticated/medicos'
      path: '/medicos'
      fullPath: '/medicos'
      preLoaderRoute: typeof AuthenticatedMedicosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notas': {
      id: '/_authenticated/notas'
      path: '/notas'
      fullPath: '/notas'
      preLoaderRoute: typeof AuthenticatedNotasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pacientes': {
      id: '/_authenticated/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof AuthenticatedPacientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ramais': {
      id: '/_authenticated/ramais'
      path: '/ramais'
      fullPath: '/ramais'
      preLoaderRoute: typeof AuthenticatedRamaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salas': {
      id: '/_authenticated/salas'
      path: '/salas'
      fullPath: '/salas'
      preLoaderRoute: typeof AuthenticatedSalasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/senhas': {
      id: '/_authenticated/senhas'
      path: '/senhas'
      fullPath: '/senhas'
      preLoaderRoute: typeof AuthenticatedSenhasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sobre': {
      id: '/_authenticated/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof AuthenticatedSobreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solicitacoes': {
      id: '/_authenticated/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/solicitacoes'
      preLoaderRoute: typeof AuthenticatedSolicitacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sondas': {
      id: '/_authenticated/sondas'
      path: '/sondas'
      fullPath: '/sondas'
      preLoaderRoute: typeof AuthenticatedSondasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedColaboradorasRoute: typeof AuthenticatedColaboradorasRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEnfermagemRoute: typeof AuthenticatedEnfermagemRoute
  AuthenticatedEscalaRoute: typeof AuthenticatedEscalaRoute
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRoute
  AuthenticatedItensRoute: typeof AuthenticatedItensRoute
  AuthenticatedMedicosRoute: typeof AuthenticatedMedicosRoute
  AuthenticatedNotasRoute: typeof AuthenticatedNotasRoute
  AuthenticatedPacientesRoute: typeof AuthenticatedPacientesRoute
  AuthenticatedRamaisRoute: typeof AuthenticatedRamaisRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedSalasRoute: typeof AuthenticatedSalasRoute
  AuthenticatedSenhasRoute: typeof AuthenticatedSenhasRoute
  AuthenticatedSobreRoute: typeof AuthenticatedSobreRoute
  AuthenticatedSolicitacoesRoute: typeof AuthenticatedSolicitacoesRoute
  AuthenticatedSondasRoute: typeof AuthenticatedSondasRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedColaboradorasRoute: AuthenticatedColaboradorasRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEnfermagemRoute: AuthenticatedEnfermagemRoute,
  AuthenticatedEscalaRoute: AuthenticatedEscalaRoute,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRoute,
  AuthenticatedItensRoute: AuthenticatedItensRoute,
  AuthenticatedMedicosRoute: AuthenticatedMedicosRoute,
  AuthenticatedNotasRoute: AuthenticatedNotasRoute,
  AuthenticatedPacientesRoute: AuthenticatedPacientesRoute,
  AuthenticatedRamaisRoute: AuthenticatedRamaisRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedSalasRoute: AuthenticatedSalasRoute,
  AuthenticatedSenhasRoute: AuthenticatedSenhasRoute,
  AuthenticatedSobreRoute: AuthenticatedSobreRoute,
  AuthenticatedSolicitacoesRoute: AuthenticatedSolicitacoesRoute,
  AuthenticatedSondasRoute: AuthenticatedSondasRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
