-- Minha Agenda de Marcação: registros pessoais por usuário.
create table if not exists public.agenda_marcacao (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  nome_paciente text not null,
  telefone text not null,
  exame text not null,
  convenio text,
  medico text,
  unidade text,
  data_prevista date not null,
  data_contato date,
  retorno_em date,
  status text not null default 'nao_agendado' check (status in ('nao_agendado','aguardando_retorno','agendado','retorno_futuro','aguardando_autorizacao','cancelado','concluido')),
  observacao text,
  observacoes_internas text,
  lembrete text,
  lembrete_em timestamptz,
  created_by uuid not null references auth.users(id) on delete cascade default auth.uid(),
  created_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now(),
  constraint agenda_marcacao_owner_match check (user_id = created_by)
);

create index if not exists agenda_marcacao_nome_idx on public.agenda_marcacao (lower(nome_paciente));
create index if not exists agenda_marcacao_telefone_idx on public.agenda_marcacao (telefone);
create index if not exists agenda_marcacao_status_idx on public.agenda_marcacao (status);
create index if not exists agenda_marcacao_data_prevista_idx on public.agenda_marcacao (data_prevista);
create index if not exists agenda_marcacao_user_data_idx on public.agenda_marcacao (user_id, data_prevista);

create trigger trg_agenda_marcacao_touch before update on public.agenda_marcacao
for each row execute function public.touch_updated_at();

comment on table public.agenda_marcacao is 'Agenda pessoal da equipe de marcação; cada registro pertence ao usuário criador.';

grant select, insert, update, delete on public.agenda_marcacao to authenticated;
grant all on public.agenda_marcacao to service_role;
grant usage, select on sequence public.agenda_marcacao_id_seq to authenticated;
alter table public.agenda_marcacao enable row level security;

drop policy if exists "agenda_marcacao_select" on public.agenda_marcacao;
drop policy if exists "agenda_marcacao_insert" on public.agenda_marcacao;
drop policy if exists "agenda_marcacao_update" on public.agenda_marcacao;
drop policy if exists "agenda_marcacao_delete" on public.agenda_marcacao;

create policy "agenda_marcacao_select" on public.agenda_marcacao
  for select to authenticated
  using (public.is_admin(auth.uid()) or (user_id = auth.uid() and public.tem_modulo(auth.uid(), 'agenda_marcacao')));

create policy "agenda_marcacao_insert" on public.agenda_marcacao
  for insert to authenticated
  with check (user_id = auth.uid() and created_by = auth.uid() and public.pode_editar(auth.uid(), 'agenda_marcacao_adicionar'));

create policy "agenda_marcacao_update" on public.agenda_marcacao
  for update to authenticated
  using (public.is_admin(auth.uid()) or (user_id = auth.uid() and public.pode_editar(auth.uid(), 'agenda_marcacao_editar')))
  with check (public.is_admin(auth.uid()) or (user_id = auth.uid() and created_by = auth.uid() and public.pode_editar(auth.uid(), 'agenda_marcacao_editar')));

create policy "agenda_marcacao_delete" on public.agenda_marcacao
  for delete to authenticated
  using (public.is_admin(auth.uid()) or (user_id = auth.uid() and public.pode_editar(auth.uid(), 'agenda_marcacao_excluir')));

-- Permissões disponíveis no catálogo da aplicação:
-- agenda_marcacao, agenda_marcacao_adicionar, agenda_marcacao_editar,
-- agenda_marcacao_excluir, agenda_marcacao_relatorios.
