-- Controle de IP: inventário de ativos de rede e reservas de endereços.
create table if not exists public.controle_ip (
  id bigint generated by default as identity primary key,
  unidade text not null check (unidade in ('MATRIZ', 'MN')),
  categoria text not null check (categoria in ('impressoras','computadores','servidores','dvr','wifi','roteadores','tv_corporativas','switch','atl','relogio_ponto')),
  ip inet,
  nome text not null,
  local text,
  andar text,
  setor text,
  patrimonio text,
  modelo text,
  fabricante text,
  mac_address text,
  porta text,
  observacoes text,
  status_online text not null default 'nao_verificado' check (status_online in ('online','offline','nao_verificado')),
  ultima_verificacao timestamptz,
  criado_por uuid references auth.users(id),
  criado_em timestamptz not null default now(),
  atualizado_por uuid references auth.users(id),
  atualizado_em timestamptz not null default now()
);

create index if not exists controle_ip_unidade_idx on public.controle_ip(unidade);
create index if not exists controle_ip_categoria_idx on public.controle_ip(categoria);
create index if not exists controle_ip_ip_idx on public.controle_ip(ip);
create index if not exists controle_ip_status_idx on public.controle_ip(status_online);
create unique index if not exists controle_ip_ip_unico on public.controle_ip(ip) where ip is not null;

grant select, insert, update, delete on public.controle_ip to authenticated;
grant usage, select on sequence public.controle_ip_id_seq to authenticated;
grant all on public.controle_ip to service_role;
alter table public.controle_ip enable row level security;

drop policy if exists controle_ip_select on public.controle_ip;
drop policy if exists controle_ip_insert on public.controle_ip;
drop policy if exists controle_ip_update on public.controle_ip;
drop policy if exists controle_ip_delete on public.controle_ip;
create policy controle_ip_select on public.controle_ip for select to authenticated
  using (public.tem_modulo(auth.uid(), 'controle_ip'));
create policy controle_ip_insert on public.controle_ip for insert to authenticated
  with check (public.is_admin(auth.uid()) or public.tem_modulo(auth.uid(), 'controle_ip_adicionar'));
create policy controle_ip_update on public.controle_ip for update to authenticated
  using (public.is_admin(auth.uid()) or public.tem_modulo(auth.uid(), 'controle_ip_editar'))
  with check (public.is_admin(auth.uid()) or public.tem_modulo(auth.uid(), 'controle_ip_editar'));
create policy controle_ip_delete on public.controle_ip for delete to authenticated
  using (public.is_admin(auth.uid()) or public.tem_modulo(auth.uid(), 'controle_ip_excluir'));

create or replace function public.controle_ip_normalizar()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.ip is not null then
    if split_part(new.ip::text, '.', 1) = '192' and split_part(new.ip::text, '.', 2) = '0' then
      new.unidade := 'MATRIZ';
    elsif split_part(new.ip::text, '.', 1) = '192' and split_part(new.ip::text, '.', 2) = '1' then
      new.unidade := 'MN';
    end if;
  end if;
  if tg_op = 'INSERT' then
    new.criado_por := coalesce(new.criado_por, auth.uid());
  end if;
  new.atualizado_por := auth.uid();
  new.atualizado_em := now();
  return new;
end;
$$;

drop trigger if exists trg_controle_ip_normalizar on public.controle_ip;
create trigger trg_controle_ip_normalizar before insert or update on public.controle_ip
for each row execute function public.controle_ip_normalizar();

create or replace function public.audit_controle_ip()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_nome text;
begin
  select nome into v_nome from public.profiles where id = auth.uid();
  insert into public.audit_logs(user_id, usuario_nome, tabela, operacao, registro_id, dados_anteriores, dados_novos)
  values (auth.uid(), coalesce(v_nome, 'sistema'), 'controle_ip', tg_op,
    coalesce(new.id, old.id)::text,
    case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) else null end,
    case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) else null end);
  return coalesce(new, old);
end;
$$;
drop trigger if exists trg_controle_ip_audit on public.controle_ip;
create trigger trg_controle_ip_audit after insert or update or delete on public.controle_ip
for each row execute function public.audit_controle_ip();
revoke execute on function public.audit_controle_ip() from public, anon, authenticated;
