-- Catálogo de nomes reutilizáveis do cronograma de atividades da Enfermagem.
create table if not exists public.atividades_enfermagem_catalogo (
  id bigint generated by default as identity primary key,
  titulo text not null unique check (length(btrim(titulo)) between 1 and 180),
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

-- Preserva e disponibiliza os títulos que já estavam cadastrados no cronograma.
insert into public.atividades_enfermagem_catalogo (titulo)
select distinct btrim(titulo)
from public.atividades_enfermagem
where length(btrim(titulo)) between 1 and 180
on conflict (titulo) do nothing;

grant select, insert on public.atividades_enfermagem_catalogo to authenticated;
grant all on public.atividades_enfermagem_catalogo to service_role;
alter table public.atividades_enfermagem_catalogo enable row level security;
drop policy if exists atividades_enfermagem_catalogo_select on public.atividades_enfermagem_catalogo;
drop policy if exists atividades_enfermagem_catalogo_insert on public.atividades_enfermagem_catalogo;
create policy atividades_enfermagem_catalogo_select
on public.atividades_enfermagem_catalogo for select to authenticated
using (public.is_admin(auth.uid()) or public.tem_modulo(auth.uid(), 'enfermagem'));
create policy atividades_enfermagem_catalogo_insert
on public.atividades_enfermagem_catalogo for insert to authenticated
with check (public.is_admin(auth.uid()) or public.pode_editar(auth.uid(), 'enfermagem'));
