-- Modelos importados de Word/PDF da escala de Enfermagem.
-- O conteúdo é JSON para permitir edição célula a célula sem alterar o arquivo original.
create table if not exists public.escalas_importadas_enfermagem (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references auth.users(id) on delete cascade,
  nome_arquivo text not null,
  titulo text not null,
  inicio date,
  fim date,
  conteudo jsonb not null default '{}'::jsonb,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create index if not exists escalas_importadas_enfermagem_usuario_idx
  on public.escalas_importadas_enfermagem (usuario_id, atualizado_em desc);

grant select, insert, update, delete on public.escalas_importadas_enfermagem to authenticated;
alter table public.escalas_importadas_enfermagem enable row level security;

drop policy if exists escalas_importadas_enfermagem_select on public.escalas_importadas_enfermagem;
create policy escalas_importadas_enfermagem_select
  on public.escalas_importadas_enfermagem for select to authenticated
  using (usuario_id = auth.uid() or public.is_admin(auth.uid()));

drop policy if exists escalas_importadas_enfermagem_insert on public.escalas_importadas_enfermagem;
create policy escalas_importadas_enfermagem_insert
  on public.escalas_importadas_enfermagem for insert to authenticated
  with check (usuario_id = auth.uid());

drop policy if exists escalas_importadas_enfermagem_update on public.escalas_importadas_enfermagem;
create policy escalas_importadas_enfermagem_update
  on public.escalas_importadas_enfermagem for update to authenticated
  using (usuario_id = auth.uid() or public.is_admin(auth.uid()))
  with check (usuario_id = auth.uid() or public.is_admin(auth.uid()));

drop policy if exists escalas_importadas_enfermagem_delete on public.escalas_importadas_enfermagem;
create policy escalas_importadas_enfermagem_delete
  on public.escalas_importadas_enfermagem for delete to authenticated
  using (usuario_id = auth.uid() or public.is_admin(auth.uid()));
