-- Pendências persistentes de validade para produtos com saldo vencido.
create table if not exists public.estoque_pendencias (
  id bigint generated by default as identity primary key,
  lote_id bigint not null unique references public.lotes(id) on delete cascade,
  item_id bigint not null references public.itens(id) on delete cascade,
  tipo text not null default 'validade',
  status text not null default 'aberta' check (status in ('aberta', 'resolvida')),
  criado_em timestamptz not null default now(),
  resolvido_em timestamptz,
  resolvido_por uuid references auth.users(id) on delete set null
);

create index if not exists estoque_pendencias_status_idx
  on public.estoque_pendencias (status, criado_em desc);

create or replace function public.sincronizar_pendencias_validade()
returns void language plpgsql security definer set search_path = public as $$
begin
  insert into public.estoque_pendencias (lote_id, item_id, tipo)
  select l.id, l.item_id, 'validade'
  from public.lotes l
  join public.itens i on i.id = l.item_id
  where l.quantidade > 0
    and l.validade is not null
    and l.validade < current_date
    and i.ativo
  on conflict (lote_id) do nothing;
end;
$$;

create or replace function public.listar_pendencias_validade()
returns table (
  id bigint,
  lote_id bigint,
  item_id bigint,
  item_nome text,
  lote text,
  validade date,
  quantidade numeric,
  status text
) language sql security definer stable set search_path = public as $$
  select p.id, p.lote_id, p.item_id, i.nome, l.lote, l.validade, l.quantidade, p.status
  from public.estoque_pendencias p
  join public.lotes l on l.id = p.lote_id
  join public.itens i on i.id = p.item_id
  where p.status = 'aberta'
    and l.quantidade > 0
    and i.ativo
  order by l.validade asc nulls last, i.nome asc;
$$;

create or replace function public.resolver_pendencia_validade(p_id bigint)
returns void language plpgsql security definer set search_path = public as $$
begin
  update public.estoque_pendencias
  set status = 'resolvida', resolvido_em = now(), resolvido_por = auth.uid()
  where id = p_id and status = 'aberta';
end;
$$;

grant execute on function public.sincronizar_pendencias_validade() to authenticated;
grant execute on function public.listar_pendencias_validade() to authenticated;
grant execute on function public.resolver_pendencia_validade(bigint) to authenticated;
