-- Escala semanal exclusiva do setor de enfermagem.
-- A tabela é independente de public.escalas, que continua atendendo salas e médicos.
insert into public.especialidades (sigla, descricao)
values ('Cardiologista', 'Cardiologista')
on conflict (sigla) do nothing;

create table if not exists public.escalas_enfermagem (
  id bigint generated by default as identity primary key,
  data date not null,
  colaboradora_id bigint not null references public.colaboradoras(id) on delete cascade,
  horario_inicio text,
  horario_fim text,
  periodo text,
  observacoes text,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null,
  constraint escalas_enfermagem_colaboradora_dia_unique unique (data, colaboradora_id)
);
create index if not exists escalas_enfermagem_data_idx on public.escalas_enfermagem (data);
create trigger trg_escalas_enfermagem_touch before update on public.escalas_enfermagem
for each row execute function public.touch_updated_at();
