-- Atalhos personalizados do dashboard, isolados por usuário.
create table if not exists public.atalhos_dashboard_usuario (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references auth.users(id) on delete cascade,
  chave text not null,
  rotulo varchar(120) not null,
  destino varchar(255) not null,
  icone varchar(40) not null default 'LayoutDashboard',
  ordem integer not null default 100,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint atalhos_dashboard_rotulo_nao_vazio check (btrim(rotulo) <> ''),
  constraint atalhos_dashboard_destino_nao_vazio check (btrim(destino) <> ''),
  constraint atalhos_dashboard_ordem_valida check (ordem >= 0),
  constraint atalhos_dashboard_usuario_chave_unica unique (usuario_id, chave)
);

comment on table public.atalhos_dashboard_usuario is
  'Atalhos criados pelo usuário no dashboard, sem interferir nos demais usuários.';

create index if not exists atalhos_dashboard_usuario_ordem_idx
  on public.atalhos_dashboard_usuario (usuario_id, ordem, rotulo);

grant select, insert, update, delete on public.atalhos_dashboard_usuario to authenticated;
alter table public.atalhos_dashboard_usuario enable row level security;

drop policy if exists atalhos_dashboard_select on public.atalhos_dashboard_usuario;
create policy atalhos_dashboard_select
  on public.atalhos_dashboard_usuario for select to authenticated
  using (usuario_id = auth.uid() and public.is_ativo(auth.uid()));

drop policy if exists atalhos_dashboard_insert on public.atalhos_dashboard_usuario;
create policy atalhos_dashboard_insert
  on public.atalhos_dashboard_usuario for insert to authenticated
  with check (usuario_id = auth.uid() and public.is_ativo(auth.uid()));

drop policy if exists atalhos_dashboard_update on public.atalhos_dashboard_usuario;
create policy atalhos_dashboard_update
  on public.atalhos_dashboard_usuario for update to authenticated
  using (usuario_id = auth.uid() and public.is_ativo(auth.uid()))
  with check (usuario_id = auth.uid() and public.is_ativo(auth.uid()));

drop policy if exists atalhos_dashboard_delete on public.atalhos_dashboard_usuario;
create policy atalhos_dashboard_delete
  on public.atalhos_dashboard_usuario for delete to authenticated
  using (usuario_id = auth.uid() and public.is_ativo(auth.uid()));
