-- Chat individual das colaboradoras de Salas com a coordenação.
create or replace function public.pode_chat_salas(_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_ativo(_user_id)
    and (
      public.is_admin(_user_id)
      or exists (
        select 1 from public.usuario_permissoes
        where user_id = _user_id and modulo = 'chat_salas'
      )
      or exists (
        select 1 from public.profiles
        where id = _user_id and lower(coalesce(setor, '')) in ('operacao', 'salas')
      )
    )
$$;

create or replace function public.chat_salas_eh_coordenadora(_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.pode_chat_salas(_user_id)
    and exists (
      select 1 from public.profiles
      where id = _user_id
        and (
          lower(coalesce(nome, '')) like '%marilia%'
          or lower(coalesce(nome, '')) like '%marília%'
        )
    )
$$;

create table if not exists public.chat_salas_mensagens (
  id bigint generated by default as identity primary key,
  remetente_id uuid not null references auth.users(id) on delete cascade,
  destinatario_id uuid not null references auth.users(id) on delete cascade,
  mensagem text not null check (char_length(btrim(mensagem)) between 1 and 4000),
  criado_em timestamptz not null default now(),
  lida_em timestamptz,
  constraint chat_salas_remetente_diferente_destinatario check (remetente_id <> destinatario_id)
);

create index if not exists chat_salas_conversa_idx
  on public.chat_salas_mensagens (remetente_id, destinatario_id, criado_em);
create index if not exists chat_salas_destinatario_idx
  on public.chat_salas_mensagens (destinatario_id, lida_em, criado_em);

grant select, insert, update on public.chat_salas_mensagens to authenticated;
alter table public.chat_salas_mensagens enable row level security;

drop policy if exists chat_salas_mensagens_select on public.chat_salas_mensagens;
create policy chat_salas_mensagens_select
  on public.chat_salas_mensagens for select to authenticated
  using (
    public.pode_chat_salas(auth.uid())
    and (
      remetente_id = auth.uid()
      or destinatario_id = auth.uid()
      or public.chat_salas_eh_coordenadora(auth.uid())
    )
  );

drop policy if exists chat_salas_mensagens_insert on public.chat_salas_mensagens;
create policy chat_salas_mensagens_insert
  on public.chat_salas_mensagens for insert to authenticated
  with check (
    public.pode_chat_salas(auth.uid())
    and remetente_id = auth.uid()
    and public.pode_chat_salas(destinatario_id)
    and (
      public.chat_salas_eh_coordenadora(auth.uid())
      or public.chat_salas_eh_coordenadora(destinatario_id)
    )
  );

drop policy if exists chat_salas_mensagens_update on public.chat_salas_mensagens;
create policy chat_salas_mensagens_update
  on public.chat_salas_mensagens for update to authenticated
  using (
    public.pode_chat_salas(auth.uid())
    and (destinatario_id = auth.uid() or public.chat_salas_eh_coordenadora(auth.uid()))
  )
  with check (
    public.pode_chat_salas(auth.uid())
    and (destinatario_id = auth.uid() or public.chat_salas_eh_coordenadora(auth.uid()))
  );

-- Permite que um usuário autorizado encontre os perfis que podem participar do chat.
drop policy if exists profiles_chat_salas_select on public.profiles;
create policy profiles_chat_salas_select
  on public.profiles for select to authenticated
  using (public.pode_chat_salas(auth.uid()));

insert into public.menu_itens
  (chave, grupo, grupo_ordem, rotulo, destino, icone, modulo, ordem, somente_admin)
values
  ('chat-salas', 'Salas', 20, 'Falar com Marília', '/chat-salas', 'MessageCircle', 'chat_salas', 70, false)
on conflict (chave) do nothing;
