-- Compatibilidade: e-mail continua sendo o identificador Auth; username é resolvido antes do login.
alter table public.profiles add column if not exists username text;
alter table public.profiles add column if not exists setor_id bigint;
alter table public.profiles add column if not exists criado_por uuid references auth.users(id) on delete set null;
alter table public.profiles add column if not exists data_cadastro timestamptz not null default now();
alter table public.profiles add column if not exists ultimo_login timestamptz;
create unique index if not exists profiles_username_lower_idx on public.profiles(lower(username)) where username is not null;

create table if not exists public.setores (
  id bigint generated by default as identity primary key,
  nome text not null unique,
  ativo boolean not null default true,
  permissoes_padrao text[] not null default '{}',
  papel_padrao public.app_role not null default 'secretaria',
  criado_por uuid references auth.users(id) on delete set null,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);
alter table public.profiles drop constraint if exists profiles_setor_id_fkey;
alter table public.profiles add constraint profiles_setor_id_fkey foreign key (setor_id) references public.setores(id) on delete set null;

insert into public.setores (nome, permissoes_padrao, papel_padrao) values
 ('Recepção', array['agenda_marcacao','enfermagem','ramais','lembretes','agenda_marcacao_adicionar'], 'recepcao'),
 ('Marcação', array['agenda_marcacao','agenda_marcacao_adicionar','agenda_marcacao_editar','lembretes','ramais'], 'marcacao'),
 ('Financeiro', array['lembretes','agenda_marcacao','controle_ip','equipamentos_us'], 'secretaria'),
 ('RH', array['colaboradoras','ausencias','banco_horas','lembretes'], 'rh'),
 ('Qualidade', array['lembretes','relatorios','equipamentos_us'], 'qualidade'),
 ('Compras', array['itens','estoque','solicitacoes','lembretes'], 'secretaria'),
 ('TI', array['controle_ip','equipamentos_us','sondas','senhas','lembretes'], 'manutencao'),
 ('Mamografia', array['salas','equipamentos_us','lembretes'], 'secretaria'),
 ('Eco', array['salas','equipamentos_us','lembretes'], 'secretaria'),
 ('Medicina Nuclear', array['salas','equipamentos_us','lembretes'], 'enfermagem'),
 ('Faturamento', array['lembretes','relatorios'], 'secretaria'),
 ('Diretoria', array['relatorios','lembretes','agenda_marcacao'], 'diretoria'),
 ('Outros', array['lembretes'], 'secretaria')
on conflict (nome) do nothing;

create table if not exists public.configuracoes_acesso (
  chave text primary key,
  valor jsonb not null default '{}'::jsonb,
  atualizado_por uuid references auth.users(id) on delete set null,
  atualizado_em timestamptz not null default now()
);
insert into public.configuracoes_acesso (chave, valor) values ('cadastro_automatico', 'true'::jsonb) on conflict (chave) do nothing;

create table if not exists public.auditoria_autenticacao (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  username text,
  email text,
  acao text not null,
  dados jsonb,
  criado_em timestamptz not null default now()
);

-- Perfis novos são criados com username informado no metadata, sem alterar usuários antigos.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_username text; v_setor_id bigint; v_setor text;
begin
  v_username := nullif(lower(trim(new.raw_user_meta_data->>'username')), '');
  v_setor := nullif(trim(new.raw_user_meta_data->>'setor'), '');
  if v_setor is not null then select id into v_setor_id from public.setores where lower(nome)=lower(v_setor) and ativo; end if;
  insert into public.profiles (id, nome, login, username, setor, setor_id, ativo, data_cadastro)
  values (new.id, coalesce(new.raw_user_meta_data->>'nome', split_part(new.email,'@',1)), new.email, v_username, v_setor, v_setor_id, true, now())
  on conflict (id) do update set username=coalesce(excluded.username, profiles.username), setor_id=coalesce(excluded.setor_id, profiles.setor_id);
  if not exists (select 1 from public.user_roles) then insert into public.user_roles (user_id, role) values (new.id, 'admin_master'); end if;
  return new;
end;
$$;

create or replace function public.is_username_available(p_username text)
returns boolean language sql stable security definer set search_path=public as $$
  select not exists (select 1 from public.profiles where lower(username)=lower(trim(p_username)))
$$;
grant execute on function public.is_username_available(text) to anon, authenticated;

grant select on public.setores to anon, authenticated;
grant select, insert, update, delete on public.setores to authenticated;
grant select, insert, update on public.configuracoes_acesso to authenticated;
grant insert on public.auditoria_autenticacao to authenticated;
grant all on public.setores, public.configuracoes_acesso, public.auditoria_autenticacao to service_role;

alter table public.setores enable row level security;
alter table public.configuracoes_acesso enable row level security;
alter table public.auditoria_autenticacao enable row level security;
drop policy if exists setores_public_select on public.setores;
drop policy if exists setores_admin_write on public.setores;
create policy setores_public_select on public.setores for select to anon, authenticated using (ativo or public.is_admin(auth.uid()));
create policy setores_admin_write on public.setores for all to authenticated using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));
drop policy if exists config_acesso_admin on public.configuracoes_acesso;
create policy config_acesso_admin on public.configuracoes_acesso for all to authenticated using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));
drop policy if exists auditoria_auth_admin on public.auditoria_autenticacao;
create policy auditoria_auth_admin on public.auditoria_autenticacao for select to authenticated using (public.is_admin(auth.uid()));
create policy auditoria_auth_insert on public.auditoria_autenticacao for insert to authenticated with check (user_id = auth.uid() or public.is_admin(auth.uid()));
