-- Cadastro de fornecedores e documentos com validade.
create table if not exists public.fornecedores (
  id bigint generated by default as identity primary key,
  nome text not null,
  cnpj text,
  telefone text,
  email text,
  observacoes text,
  ativo boolean not null default true,
  criado_por uuid references auth.users(id) on delete set null default auth.uid(),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.fornecedor_documentos (
  id bigint generated by default as identity primary key,
  fornecedor_id bigint not null references public.fornecedores(id) on delete cascade,
  nome text not null,
  numero text,
  validade date,
  observacoes text,
  criado_por uuid references auth.users(id) on delete set null default auth.uid(),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create index if not exists fornecedores_nome_idx on public.fornecedores (lower(nome));
create index if not exists fornecedor_documentos_validade_idx on public.fornecedor_documentos (validade);
create index if not exists fornecedor_documentos_fornecedor_idx on public.fornecedor_documentos (fornecedor_id, validade);

drop trigger if exists trg_fornecedores_touch on public.fornecedores;
create trigger trg_fornecedores_touch before update on public.fornecedores
for each row execute function public.touch_updated_at();
drop trigger if exists trg_fornecedor_documentos_touch on public.fornecedor_documentos;
create trigger trg_fornecedor_documentos_touch before update on public.fornecedor_documentos
for each row execute function public.touch_updated_at();

grant select, insert, update, delete on public.fornecedores, public.fornecedor_documentos to authenticated;
grant all on public.fornecedores, public.fornecedor_documentos to service_role;
alter table public.fornecedores enable row level security;
alter table public.fornecedor_documentos enable row level security;

drop policy if exists fornecedores_select on public.fornecedores;
drop policy if exists fornecedores_write on public.fornecedores;
create policy fornecedores_select on public.fornecedores for select to authenticated
  using (public.is_admin(auth.uid()) or public.tem_modulo(auth.uid(), 'fornecedores'));
create policy fornecedores_write on public.fornecedores for all to authenticated
  using (public.is_admin(auth.uid()) or public.pode_editar(auth.uid(), 'fornecedores'))
  with check (public.is_admin(auth.uid()) or public.pode_editar(auth.uid(), 'fornecedores'));

drop policy if exists fornecedor_documentos_select on public.fornecedor_documentos;
drop policy if exists fornecedor_documentos_write on public.fornecedor_documentos;
create policy fornecedor_documentos_select on public.fornecedor_documentos for select to authenticated
  using (public.is_admin(auth.uid()) or public.tem_modulo(auth.uid(), 'fornecedores'));
create policy fornecedor_documentos_write on public.fornecedor_documentos for all to authenticated
  using (public.is_admin(auth.uid()) or public.pode_editar(auth.uid(), 'fornecedores'))
  with check (public.is_admin(auth.uid()) or public.pode_editar(auth.uid(), 'fornecedores'));

-- Integra com a Lixeira criada anteriormente, quando essa migration já estiver aplicada.
do $do$
begin
  if to_regprocedure('public.enviar_para_lixeira()') is not null then
    drop trigger if exists trg_lixeira_delete on public.fornecedores;
    create trigger trg_lixeira_delete after delete on public.fornecedores
      for each row execute function public.enviar_para_lixeira();
    drop trigger if exists trg_lixeira_delete on public.fornecedor_documentos;
    create trigger trg_lixeira_delete after delete on public.fornecedor_documentos
      for each row execute function public.enviar_para_lixeira();
  end if;
end $do$;
