-- Lembretes pessoais com alertas, recorrência e RLS.
alter table public.profiles
  add column if not exists preferencias_lembretes jsonb not null default '{"som":false,"popup":true}'::jsonb;

create table if not exists public.lembretes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  titulo text not null,
  descricao text,
  categoria text not null default 'outros',
  prioridade text not null default 'media' check (prioridade in ('alta','media','baixa')),
  data_lembrete date not null,
  hora_lembrete time,
  recorrencia text not null default 'nenhuma' check (recorrencia in ('nenhuma','diaria','semanal','mensal','anual','personalizada')),
  recorrencia_dias integer check (recorrencia_dias is null or recorrencia_dias between 1 and 3650),
  status text not null default 'pendente' check (status in ('pendente','concluido','adiado')),
  som_ativo boolean not null default false,
  popup_ativo boolean not null default true,
  observacoes text,
  vinculo_tipo text,
  vinculo_id bigint,
  criado_por uuid not null references auth.users(id) on delete cascade default auth.uid(),
  criado_em timestamptz not null default now(),
  atualizado_por uuid references auth.users(id) on delete set null,
  atualizado_em timestamptz not null default now(),
  concluido_em timestamptz,
  adiado_ate timestamptz,
  constraint lembretes_owner_match check (user_id = criado_por)
);

create index if not exists lembretes_user_data_idx on public.lembretes (user_id, data_lembrete, status);
create index if not exists lembretes_categoria_idx on public.lembretes (categoria);
create index if not exists lembretes_prioridade_idx on public.lembretes (prioridade);
create index if not exists lembretes_status_idx on public.lembretes (status);
create index if not exists lembretes_titulo_idx on public.lembretes (lower(titulo));

create trigger trg_lembretes_touch before update on public.lembretes
for each row execute function public.touch_updated_at();

grant select, insert, update, delete on public.lembretes to authenticated;
grant all on public.lembretes to service_role;
grant usage, select on sequence public.lembretes_id_seq to authenticated;
alter table public.lembretes enable row level security;

drop policy if exists "lembretes_select" on public.lembretes;
drop policy if exists "lembretes_insert" on public.lembretes;
drop policy if exists "lembretes_update" on public.lembretes;
drop policy if exists "lembretes_delete" on public.lembretes;

create policy "lembretes_select" on public.lembretes
  for select to authenticated
  using (public.is_admin(auth.uid()) or public.tem_modulo(auth.uid(), 'lembretes_visualizar_todos') or (user_id = auth.uid() and public.tem_modulo(auth.uid(), 'lembretes')));

create policy "lembretes_insert" on public.lembretes
  for insert to authenticated
  with check (user_id = auth.uid() and criado_por = auth.uid() and public.pode_editar(auth.uid(), 'lembretes_adicionar'));

create policy "lembretes_update" on public.lembretes
  for update to authenticated
  using (public.is_admin(auth.uid()) or (user_id = auth.uid() and public.pode_editar(auth.uid(), 'lembretes_editar')))
  with check (public.is_admin(auth.uid()) or (user_id = auth.uid() and criado_por = auth.uid() and public.pode_editar(auth.uid(), 'lembretes_editar')));

create policy "lembretes_delete" on public.lembretes
  for delete to authenticated
  using (public.is_admin(auth.uid()) or (user_id = auth.uid() and public.pode_editar(auth.uid(), 'lembretes_excluir')));
