-- Módulo independente de MARCAÇÃO: catálogos próprios, escala semanal e chat privado.
-- Colaboradores do setor recebem leitura; a conta individual da coordenadora recebe escrita na escala.

-- -------------------- Setor e permissões padrão --------------------
insert into public.setores as setor (nome, papel_padrao, permissoes_padrao)
values (
  'Marcação',
  'marcacao',
  array[
    'marcacao_acessar',
    'marcacao_escala_visualizar',
    'marcacao_medicos_visualizar',
    'marcacao_colaboradores_visualizar',
    'chat_marcacao'
  ]::text[]
)
on conflict (nome) do update
set papel_padrao = excluded.papel_padrao,
    permissoes_padrao = array(
  select distinct permissao
  from unnest(
    array(
      select permissao
      from unnest(coalesce(setor.permissoes_padrao, '{}'::text[])) as antigo(permissao)
      where permissao not in (
        'marcacao_escala_adicionar',
        'marcacao_escala_editar',
        'marcacao_escala_excluir',
        'marcacao_coordenacao',
        'chat_marcacao_coordenacao'
      )
    ) || excluded.permissoes_padrao
  ) as p(permissao)
  order by permissao
),
    atualizado_em = now();

-- -------------------- Catálogos isolados --------------------
create table if not exists public.marcacao_medicos (
  id bigint generated by default as identity primary key,
  nome text not null check (btrim(nome) <> ''),
  apelido text,
  crm text,
  especialidade_principal text,
  especialidades text,
  procedimentos text,
  observacoes text,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists marcacao_medicos_nome_idx
  on public.marcacao_medicos (lower(nome));
create index if not exists marcacao_medicos_ativos_idx
  on public.marcacao_medicos (ativo, lower(nome));

create table if not exists public.marcacao_colaboradores (
  id bigint generated by default as identity primary key,
  nome text not null check (btrim(nome) <> ''),
  cargo text,
  entrada time,
  saida time,
  observacoes text,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists marcacao_colaboradores_ativos_idx
  on public.marcacao_colaboradores (ativo, lower(nome));

-- Cópia inicial, sem FK, sincronização ou vínculo operacional com os médicos de Salas.
insert into public.marcacao_medicos (
  nome, apelido, crm, especialidade_principal, especialidades, procedimentos, observacoes, ativo
)
select
  m.nome, m.apelido, m.crm, m.especialidade_principal, m.especialidades, m.procedimentos, m.observacoes, m.ativo
from public.medicos m
where m.setor = 'operacao'
  and not exists (
    select 1
    from public.marcacao_medicos mm
    where lower(mm.nome) = lower(m.nome)
      and coalesce(nullif(btrim(mm.crm), ''), '') = coalesce(nullif(btrim(m.crm), ''), '')
  );

-- -------------------- Escala semanal independente --------------------
create table if not exists public.marcacao_escalas (
  id bigint generated by default as identity primary key,
  data date not null,
  medico_id bigint not null references public.marcacao_medicos(id) on delete restrict,
  horario_inicio time,
  horario_fim time,
  observacoes text,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint marcacao_escalas_horario_valido
    check (horario_inicio is null or horario_fim is null or horario_fim > horario_inicio)
);

create index if not exists marcacao_escalas_data_idx
  on public.marcacao_escalas (data, horario_inicio, medico_id);

create table if not exists public.marcacao_escala_colaboradores (
  escala_id bigint not null references public.marcacao_escalas(id) on delete cascade,
  colaboradora_id bigint not null references public.marcacao_colaboradores(id) on delete restrict,
  primary key (escala_id, colaboradora_id)
);

create index if not exists marcacao_escala_colaboradores_pessoa_idx
  on public.marcacao_escala_colaboradores (colaboradora_id, escala_id);

-- -------------------- RLS: todos do setor leem; gestão de catálogos é administrativa --------------------
grant select, insert, update, delete on public.marcacao_medicos to authenticated;
grant select, insert, update, delete on public.marcacao_colaboradores to authenticated;
grant select, insert, update, delete on public.marcacao_escalas to authenticated;
grant select, insert, update, delete on public.marcacao_escala_colaboradores to authenticated;
grant usage, select on sequence public.marcacao_medicos_id_seq to authenticated;
grant usage, select on sequence public.marcacao_colaboradores_id_seq to authenticated;
grant usage, select on sequence public.marcacao_escalas_id_seq to authenticated;
grant all on public.marcacao_medicos, public.marcacao_colaboradores, public.marcacao_escalas,
  public.marcacao_escala_colaboradores to service_role;

alter table public.marcacao_medicos enable row level security;
alter table public.marcacao_colaboradores enable row level security;
alter table public.marcacao_escalas enable row level security;
alter table public.marcacao_escala_colaboradores enable row level security;

-- A autorização é explícita: is_admin/tem_modulo não devem dar escrita na escala a outras contas.
create or replace function public.pode_editar_escala_marcacao(_user_id uuid, _modulo text)
returns boolean
language sql stable security definer
set search_path = public
as $$
  select public.is_ativo(_user_id)
     and _modulo = any (array[
       'marcacao_escala_adicionar', 'marcacao_escala_editar', 'marcacao_escala_excluir'
     ]::text[])
     and exists (
       select 1 from public.usuario_permissoes
       where user_id = _user_id and modulo = _modulo
     )
$$;
revoke all on function public.pode_editar_escala_marcacao(uuid, text) from public, anon;
grant execute on function public.pode_editar_escala_marcacao(uuid, text) to authenticated;

create policy marcacao_medicos_read on public.marcacao_medicos
for select to authenticated
using (public.tem_modulo(auth.uid(), 'marcacao_medicos_visualizar'));
create policy marcacao_medicos_admin_manage on public.marcacao_medicos
for all to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

create policy marcacao_colaboradores_read on public.marcacao_colaboradores
for select to authenticated
using (public.tem_modulo(auth.uid(), 'marcacao_colaboradores_visualizar'));
create policy marcacao_colaboradores_admin_manage on public.marcacao_colaboradores
for all to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

create policy marcacao_escalas_read on public.marcacao_escalas
for select to authenticated
using (public.tem_modulo(auth.uid(), 'marcacao_escala_visualizar'));
create policy marcacao_escalas_add on public.marcacao_escalas
for insert to authenticated
with check (
  public.tem_modulo(auth.uid(), 'marcacao_escala_visualizar')
  and public.pode_editar_escala_marcacao(auth.uid(), 'marcacao_escala_adicionar')
);
create policy marcacao_escalas_edit on public.marcacao_escalas
for update to authenticated
using (
  public.tem_modulo(auth.uid(), 'marcacao_escala_visualizar')
  and public.pode_editar_escala_marcacao(auth.uid(), 'marcacao_escala_editar')
)
with check (
  public.tem_modulo(auth.uid(), 'marcacao_escala_visualizar')
  and public.pode_editar_escala_marcacao(auth.uid(), 'marcacao_escala_editar')
);
create policy marcacao_escalas_delete on public.marcacao_escalas
for delete to authenticated
using (
  public.tem_modulo(auth.uid(), 'marcacao_escala_visualizar')
  and public.pode_editar_escala_marcacao(auth.uid(), 'marcacao_escala_excluir')
);

create policy marcacao_escala_colaboradores_read on public.marcacao_escala_colaboradores
for select to authenticated
using (
  exists (
    select 1 from public.marcacao_escalas e
    where e.id = escala_id and public.tem_modulo(auth.uid(), 'marcacao_escala_visualizar')
  )
);
create policy marcacao_escala_colaboradores_add on public.marcacao_escala_colaboradores
for insert to authenticated
with check (
  exists (
    select 1 from public.marcacao_escalas e
    where e.id = escala_id and public.tem_modulo(auth.uid(), 'marcacao_escala_visualizar')
  )
  and public.pode_editar_escala_marcacao(auth.uid(), 'marcacao_escala_editar')
);
create policy marcacao_escala_colaboradores_edit on public.marcacao_escala_colaboradores
for update to authenticated
using (
  exists (
    select 1 from public.marcacao_escalas e
    where e.id = escala_id and public.tem_modulo(auth.uid(), 'marcacao_escala_visualizar')
  )
  and public.pode_editar_escala_marcacao(auth.uid(), 'marcacao_escala_editar')
)
with check (
  exists (
    select 1 from public.marcacao_escalas e
    where e.id = escala_id and public.tem_modulo(auth.uid(), 'marcacao_escala_visualizar')
  )
  and public.pode_editar_escala_marcacao(auth.uid(), 'marcacao_escala_editar')
);
create policy marcacao_escala_colaboradores_delete on public.marcacao_escala_colaboradores
for delete to authenticated
using (
  exists (
    select 1 from public.marcacao_escalas e
    where e.id = escala_id and public.tem_modulo(auth.uid(), 'marcacao_escala_visualizar')
  )
  and public.pode_editar_escala_marcacao(auth.uid(), 'marcacao_escala_editar')
);

-- Salva cabeçalho e vínculos numa única transação, mantendo a autorização RLS do usuário.
create or replace function public.salvar_marcacao_escala(
  p_id bigint,
  p_data date,
  p_medico_id bigint,
  p_horario_inicio time,
  p_horario_fim time,
  p_observacoes text,
  p_colaboradora_ids bigint[] default '{}'
)
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_id bigint;
  v_perm text;
begin
  if auth.uid() is null or not public.tem_modulo(auth.uid(), 'marcacao_escala_visualizar') then
    raise exception 'Sem acesso à escala de Marcação';
  end if;

  v_perm := case when p_id is null then 'marcacao_escala_adicionar' else 'marcacao_escala_editar' end;
  if not public.pode_editar_escala_marcacao(auth.uid(), v_perm) then
    raise exception 'Sem permissão para salvar esta escala';
  end if;

  if p_horario_inicio is not null and p_horario_fim is not null and p_horario_fim <= p_horario_inicio then
    raise exception 'O horário final deve ser posterior ao inicial';
  end if;

  if not exists (select 1 from public.marcacao_medicos where id = p_medico_id and ativo) then
    raise exception 'Selecione um médico ativo da Marcação';
  end if;

  if exists (
    select 1
    from unnest(coalesce(p_colaboradora_ids, '{}'::bigint[])) as selecionada(id)
    left join public.marcacao_colaboradores c on c.id = selecionada.id
    where c.id is null or not c.ativo
  ) then
    raise exception 'A escala contém uma colaboradora inativa ou inexistente';
  end if;

  if p_id is null then
    insert into public.marcacao_escalas (
      data, medico_id, horario_inicio, horario_fim, observacoes, created_by, updated_by
    ) values (
      p_data, p_medico_id, p_horario_inicio, p_horario_fim, nullif(btrim(p_observacoes), ''), auth.uid(), auth.uid()
    ) returning id into v_id;
  else
    update public.marcacao_escalas
       set data = p_data,
           medico_id = p_medico_id,
           horario_inicio = p_horario_inicio,
           horario_fim = p_horario_fim,
           observacoes = nullif(btrim(p_observacoes), ''),
           updated_by = auth.uid(),
           updated_at = now()
     where id = p_id
     returning id into v_id;
    if v_id is null then raise exception 'Escala não encontrada ou sem permissão para editar'; end if;
  end if;

  delete from public.marcacao_escala_colaboradores where escala_id = v_id;
  insert into public.marcacao_escala_colaboradores (escala_id, colaboradora_id)
  select v_id, selecionada.id
  from (select distinct unnest(coalesce(p_colaboradora_ids, '{}'::bigint[])) as id) selecionada;

  return v_id;
end;
$$;
revoke all on function public.salvar_marcacao_escala(bigint, date, bigint, time, time, text, bigint[]) from public, anon;
grant execute on function public.salvar_marcacao_escala(bigint, date, bigint, time, time, text, bigint[]) to authenticated;

-- Exclusões de escalas compartilhadas usam a Lixeira global de 7 dias.
drop trigger if exists trg_lixeira_delete on public.marcacao_escalas;
create trigger trg_lixeira_delete after delete on public.marcacao_escalas
for each row execute function public.enviar_para_lixeira();
drop trigger if exists trg_lixeira_delete on public.marcacao_escala_colaboradores;
create trigger trg_lixeira_delete after delete on public.marcacao_escala_colaboradores
for each row execute function public.enviar_para_lixeira();

-- -------------------- Permissões padrão e perfil individual da Geise --------------------
insert into public.usuario_permissoes (user_id, modulo)
select p.id, permissao
from public.profiles p
cross join unnest(array[
  'marcacao_acessar',
  'marcacao_escala_visualizar',
  'marcacao_medicos_visualizar',
  'marcacao_colaboradores_visualizar',
  'chat_marcacao'
]::text[]) as m(permissao)
where lower(coalesce(p.setor, '')) in ('marcação', 'marcacao')
   or p.setor_id = (select id from public.setores where lower(nome) in ('marcação', 'marcacao') order by id limit 1)
on conflict (user_id, modulo) do nothing;

do $$
declare
  v_geise uuid;
  v_setor_id bigint;
begin
  select id into v_setor_id
  from public.setores
  where lower(nome) in ('marcação', 'marcacao')
  order by id
  limit 1;

  select p.id into v_geise
  from public.profiles p
  join auth.users u on u.id = p.id
  where lower(u.email) = 'marcacao@clinicaceu.com.br'
  order by p.id
  limit 1;

  delete from public.usuario_permissoes
  where modulo = any(array[
    'marcacao_escala_adicionar',
    'marcacao_escala_editar',
    'marcacao_escala_excluir',
    'marcacao_coordenacao',
    'chat_marcacao_coordenacao'
  ]::text[])
    and (v_geise is null or user_id <> v_geise);

  if v_geise is null then
    raise notice 'Conta da coordenadora de Marcação não encontrada; o perfil individual será aplicado quando ela estiver cadastrada.';
    return;
  end if;

  update public.profiles
     set nome = 'Geisiane Taise Gomes Moraes',
         setor = 'Marcação',
         setor_id = v_setor_id
   where id = v_geise;

  -- Define o perfil de coordenadora; preserva apenas um eventual Administrador Master.
  if not public.is_master(v_geise) then
    delete from public.user_roles where user_id = v_geise;
    insert into public.user_roles (user_id, role) values (v_geise, 'marcacao')
    on conflict (user_id, role) do nothing;
  end if;

  insert into public.usuario_permissoes (user_id, modulo)
  select v_geise, permissao
  from unnest(array[
    'marcacao_acessar',
    'marcacao_escala_visualizar',
    'marcacao_escala_adicionar',
    'marcacao_escala_editar',
    'marcacao_escala_excluir',
    'marcacao_medicos_visualizar',
    'marcacao_colaboradores_visualizar',
    'marcacao_coordenacao',
    'chat_marcacao',
    'chat_marcacao_coordenacao'
  ]::text[]) as m(permissao)
  on conflict (user_id, modulo) do nothing;
end;
$$;

-- -------------------- Menu principal: grupo MARCAÇÃO --------------------
insert into public.menu_itens
  (chave, grupo, grupo_ordem, rotulo, destino, icone, modulo, ordem, somente_admin)
values
  ('marcacao-escala', 'Marcação', 45, 'Escala semanal', '/marcacao', 'CalendarDays', 'marcacao_escala_visualizar', 10, false),
  ('marcacao-medicos', 'Marcação', 45, 'Médicos', '/marcacao-medicos', 'Stethoscope', 'marcacao_medicos_visualizar', 20, false),
  ('marcacao-colaboradores', 'Marcação', 45, 'Colaboradores', '/marcacao-colaboradores', 'Users', 'marcacao_colaboradores_visualizar', 30, false),
  ('chat-marcacao', 'Marcação', 45, 'Chat da Marcação', '/chat-marcacao', 'MessageCircle', 'chat_marcacao', 40, false)
on conflict (chave) do nothing;

-- -------------------- Chat privado e direcionado --------------------
create or replace function public.chat_marcacao_eh_coordenadora(_user_id uuid)
returns boolean
language sql stable security definer
set search_path = public
as $$
  select public.is_ativo(_user_id)
     and exists (
       select 1 from public.usuario_permissoes
       where user_id = _user_id and modulo = 'marcacao_coordenacao'
     )
$$;

create or replace function public.chat_marcacao_eh_colaborador(_user_id uuid)
returns boolean
language sql stable security definer
set search_path = public
as $$
  select public.is_ativo(_user_id)
     and not public.chat_marcacao_eh_coordenadora(_user_id)
     and (
       exists (
         select 1 from public.profiles p
         where p.id = _user_id and lower(coalesce(p.setor, '')) in ('marcação', 'marcacao')
       )
       or public.has_role(_user_id, 'marcacao'::public.app_role)
     )
$$;

create or replace function public.pode_chat_marcacao(_user_id uuid)
returns boolean
language sql stable security definer
set search_path = public
as $$
  select public.is_ativo(_user_id)
     and (
       public.is_master(_user_id)
       or public.is_admin(_user_id)
       or public.chat_marcacao_eh_coordenadora(_user_id)
       or public.chat_marcacao_eh_colaborador(_user_id)
       or public.chat_coordenadora_entre_setores(_user_id)
     )
$$;

create or replace function public.chat_marcacao_pode_conversar(_remetente uuid, _destinatario uuid)
returns boolean
language sql stable security definer
set search_path = public
as $$
  select _remetente is not null
     and _destinatario is not null
     and _remetente <> _destinatario
     and public.is_ativo(_remetente)
     and public.is_ativo(_destinatario)
     and (
       (
         public.chat_marcacao_eh_coordenadora(_remetente)
         and (
           public.chat_marcacao_eh_colaborador(_destinatario)
           or public.chat_coordenadora_entre_setores(_destinatario)
           or public.is_master(_destinatario)
           or public.is_admin(_destinatario)
         )
       )
       or
       (
         public.chat_marcacao_eh_coordenadora(_destinatario)
         and (
           public.chat_marcacao_eh_colaborador(_remetente)
           or public.chat_coordenadora_entre_setores(_remetente)
           or public.is_master(_remetente)
           or public.is_admin(_remetente)
         )
       )
     )
$$;

create or replace function public.obter_chat_marcacao_contatos()
returns table (id uuid, nome text, setor text, ativo boolean, tipo text)
language sql stable security definer
set search_path = public, auth
as $$
  select distinct p.id, p.nome, p.setor, p.ativo,
    case
      when public.chat_marcacao_eh_coordenadora(p.id) then 'Coordenadora de Marcação'
      when public.is_master(p.id) then 'Administrador Master'
      when public.is_admin(p.id) then 'Administrador'
      when public.chat_coordenadora_entre_setores(p.id) then 'Coordenação'
      else 'Colaborador de Marcação'
    end as tipo
  from public.profiles p
  join auth.users u on u.id = p.id
  where auth.uid() is not null
    and public.pode_chat_marcacao(auth.uid())
    and p.ativo = true
    and p.id <> auth.uid()
    and (
      (
        public.chat_marcacao_eh_coordenadora(auth.uid())
        and (
          public.chat_marcacao_eh_colaborador(p.id)
          or public.chat_coordenadora_entre_setores(p.id)
          or public.is_master(p.id)
          or public.is_admin(p.id)
        )
      )
      or
      (
        (
          public.chat_marcacao_eh_colaborador(auth.uid())
          or public.chat_coordenadora_entre_setores(auth.uid())
          or public.is_master(auth.uid())
          or public.is_admin(auth.uid())
        )
        and public.chat_marcacao_eh_coordenadora(p.id)
      )
    )
  order by p.nome
$$;

revoke all on function public.chat_marcacao_eh_coordenadora(uuid) from public, anon;
revoke all on function public.chat_marcacao_eh_colaborador(uuid) from public, anon;
revoke all on function public.pode_chat_marcacao(uuid) from public, anon;
revoke all on function public.chat_marcacao_pode_conversar(uuid, uuid) from public, anon;
revoke all on function public.obter_chat_marcacao_contatos() from public, anon;
grant execute on function public.chat_marcacao_eh_coordenadora(uuid) to authenticated;
grant execute on function public.chat_marcacao_eh_colaborador(uuid) to authenticated;
grant execute on function public.pode_chat_marcacao(uuid) to authenticated;
grant execute on function public.chat_marcacao_pode_conversar(uuid, uuid) to authenticated;
grant execute on function public.obter_chat_marcacao_contatos() to authenticated;

create table if not exists public.chat_marcacao_mensagens (
  id bigint generated by default as identity primary key,
  remetente_id uuid not null references auth.users(id) on delete cascade,
  destinatario_id uuid not null references auth.users(id) on delete cascade,
  mensagem text,
  criado_em timestamptz not null default now(),
  lida_em timestamptz,
  anexo_path text,
  anexo_nome text,
  anexo_tipo text,
  anexo_tamanho integer,
  constraint chat_marcacao_partes_distintas check (remetente_id <> destinatario_id),
  constraint chat_marcacao_conteudo_valido check (
    (nullif(btrim(mensagem), '') is not null and char_length(mensagem) <= 4000)
    or anexo_path is not null
  ),
  constraint chat_marcacao_anexo_valido check (
    anexo_path is null or (btrim(anexo_path) <> '' and coalesce(anexo_tamanho, 0) <= 10485760)
  )
);

create index if not exists chat_marcacao_conversa_idx
  on public.chat_marcacao_mensagens (remetente_id, destinatario_id, criado_em);
create index if not exists chat_marcacao_destinatario_idx
  on public.chat_marcacao_mensagens (destinatario_id, lida_em, criado_em);

alter table public.chat_marcacao_mensagens enable row level security;
grant select, insert on public.chat_marcacao_mensagens to authenticated;
grant update (lida_em) on public.chat_marcacao_mensagens to authenticated;
grant usage, select on sequence public.chat_marcacao_mensagens_id_seq to authenticated;
grant all on public.chat_marcacao_mensagens to service_role;

create policy chat_marcacao_mensagens_read on public.chat_marcacao_mensagens
for select to authenticated
using (
  public.pode_chat_marcacao(auth.uid())
  and auth.uid() in (remetente_id, destinatario_id)
  and public.chat_marcacao_pode_conversar(remetente_id, destinatario_id)
);
create policy chat_marcacao_mensagens_send on public.chat_marcacao_mensagens
for insert to authenticated
with check (
  public.pode_chat_marcacao(auth.uid())
  and remetente_id = auth.uid()
  and public.chat_marcacao_pode_conversar(remetente_id, destinatario_id)
);
create policy chat_marcacao_mensagens_read_receipt on public.chat_marcacao_mensagens
for update to authenticated
using (
  destinatario_id = auth.uid()
  and public.chat_marcacao_pode_conversar(remetente_id, destinatario_id)
)
with check (
  destinatario_id = auth.uid()
  and public.chat_marcacao_pode_conversar(remetente_id, destinatario_id)
);

-- Bucket privado separado; tamanho e MIME são impostos também pelo Storage.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'marcacao-chat-anexos',
  'marcacao-chat-anexos',
  false,
  10485760,
  array[
    'image/png', 'image/jpeg', 'image/gif', 'image/webp', 'application/pdf', 'text/plain',
    'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
  ]::text[]
)
on conflict (id) do update
set public = false, file_size_limit = 10485760, allowed_mime_types = excluded.allowed_mime_types;

create or replace function public.chat_marcacao_anexo_autorizado(_remetente text, _destinatario text)
returns boolean
language plpgsql stable security definer
set search_path = public, auth
as $$
declare
  v_remetente uuid;
  v_destinatario uuid;
begin
  if _remetente !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
     or _destinatario !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' then
    return false;
  end if;
  v_remetente := _remetente::uuid;
  v_destinatario := _destinatario::uuid;
  return auth.uid() in (v_remetente, v_destinatario)
    and public.chat_marcacao_pode_conversar(v_remetente, v_destinatario);
end;
$$;
revoke all on function public.chat_marcacao_anexo_autorizado(text, text) from public, anon;
grant execute on function public.chat_marcacao_anexo_autorizado(text, text) to authenticated;

create policy marcacao_chat_anexos_insert on storage.objects
for insert to authenticated
with check (
  bucket_id = 'marcacao-chat-anexos'
  and (storage.foldername(name))[1] = auth.uid()::text
  and public.chat_marcacao_anexo_autorizado(
    (storage.foldername(name))[1], (storage.foldername(name))[2]
  )
);
create policy marcacao_chat_anexos_select on storage.objects
for select to authenticated
using (
  bucket_id = 'marcacao-chat-anexos'
  and public.chat_marcacao_anexo_autorizado(
    (storage.foldername(name))[1], (storage.foldername(name))[2]
  )
);
create policy marcacao_chat_anexos_delete on storage.objects
for delete to authenticated
using (
  bucket_id = 'marcacao-chat-anexos'
  and (storage.foldername(name))[1] = auth.uid()::text
  and public.chat_marcacao_anexo_autorizado(
    (storage.foldername(name))[1], (storage.foldername(name))[2]
  )
);
