-- Fila segura para integração futura com Activepieces/n8n e robô do Clinux.
-- Nesta fase nenhuma tarefa altera o Clinux automaticamente.

create table if not exists public.agendamento_automacao_tarefas (
  id uuid primary key default gen_random_uuid(),
  status text not null default 'aguardando_robo' check (status in ('aguardando_robo', 'opcoes_disponiveis', 'aguardando_aprovacao', 'aprovada', 'concluida', 'falhou', 'cancelada')),
  medico_id text not null,
  medico_nome text not null,
  exame text,
  convenio text,
  idade integer,
  turno text,
  solicitante text,
  dados_validacao jsonb not null default '{}'::jsonb,
  opcoes_horarios jsonb not null default '[]'::jsonb,
  horario_escolhido jsonb,
  protocolo text,
  referencia_externa text,
  erro text,
  criado_por uuid not null references auth.users(id),
  aprovado_por uuid references auth.users(id),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  aprovado_em timestamptz,
  concluido_em timestamptz
);

create index if not exists agendamento_automacao_tarefas_status_idx
  on public.agendamento_automacao_tarefas(status, criado_em desc);
create index if not exists agendamento_automacao_tarefas_criado_por_idx
  on public.agendamento_automacao_tarefas(criado_por, criado_em desc);

create table if not exists public.agendamento_automacao_logs (
  id bigint generated by default as identity primary key,
  tarefa_id uuid not null references public.agendamento_automacao_tarefas(id) on delete cascade,
  evento text not null,
  status text,
  detalhes jsonb not null default '{}'::jsonb,
  criado_por uuid references auth.users(id),
  criado_em timestamptz not null default now()
);

create index if not exists agendamento_automacao_logs_tarefa_idx
  on public.agendamento_automacao_logs(tarefa_id, criado_em desc);

grant select, insert, update on public.agendamento_automacao_tarefas to authenticated;
grant select, insert on public.agendamento_automacao_logs to authenticated;
grant all on public.agendamento_automacao_tarefas to service_role;
grant all on public.agendamento_automacao_logs to service_role;

alter table public.agendamento_automacao_tarefas enable row level security;
alter table public.agendamento_automacao_logs enable row level security;

drop policy if exists agendamento_automacao_tarefas_select on public.agendamento_automacao_tarefas;
create policy agendamento_automacao_tarefas_select
on public.agendamento_automacao_tarefas for select to authenticated
using (
  public.tem_modulo(auth.uid(), 'agendamento_marcacao_automacao')
  and (criado_por = auth.uid() or public.is_admin(auth.uid()))
);

drop policy if exists agendamento_automacao_tarefas_insert on public.agendamento_automacao_tarefas;
create policy agendamento_automacao_tarefas_insert
on public.agendamento_automacao_tarefas for insert to authenticated
with check (
  public.tem_modulo(auth.uid(), 'agendamento_marcacao_automacao')
  and criado_por = auth.uid()
);

drop policy if exists agendamento_automacao_tarefas_update on public.agendamento_automacao_tarefas;
create policy agendamento_automacao_tarefas_update
on public.agendamento_automacao_tarefas for update to authenticated
using (public.tem_modulo(auth.uid(), 'agendamento_marcacao_automacao') and (criado_por = auth.uid() or public.is_admin(auth.uid())))
with check (public.tem_modulo(auth.uid(), 'agendamento_marcacao_automacao') and (criado_por = auth.uid() or public.is_admin(auth.uid())));

drop policy if exists agendamento_automacao_logs_select on public.agendamento_automacao_logs;
create policy agendamento_automacao_logs_select
on public.agendamento_automacao_logs for select to authenticated
using (
  public.tem_modulo(auth.uid(), 'agendamento_marcacao_automacao')
  and exists (
    select 1 from public.agendamento_automacao_tarefas t
    where t.id = tarefa_id and (t.criado_por = auth.uid() or public.is_admin(auth.uid()))
  )
);

drop policy if exists agendamento_automacao_logs_insert on public.agendamento_automacao_logs;
create policy agendamento_automacao_logs_insert
on public.agendamento_automacao_logs for insert to authenticated
with check (
  public.tem_modulo(auth.uid(), 'agendamento_marcacao_automacao')
  and criado_por = auth.uid()
);

create or replace function public.agendamento_automacao_set_updated_at()
returns trigger language plpgsql security invoker set search_path = public
as $$
begin
  new.atualizado_em = now();
  return new;
end;
$$;

drop trigger if exists agendamento_automacao_tarefas_updated_at on public.agendamento_automacao_tarefas;
create trigger agendamento_automacao_tarefas_updated_at
before update on public.agendamento_automacao_tarefas
for each row execute function public.agendamento_automacao_set_updated_at();

insert into public.menu_itens (chave, grupo, grupo_ordem, rotulo, destino, icone, modulo, ordem, somente_admin)
values ('agendamento-automacao', 'Marcação', 50, 'Fila de automação', '/agendamento-marcacao', 'Bot', 'agendamento_marcacao_automacao', 38, false)
on conflict (chave) do update set
  rotulo = excluded.rotulo,
  destino = excluded.destino,
  icone = excluded.icone,
  modulo = excluded.modulo,
  ordem = excluded.ordem,
  somente_admin = excluded.somente_admin;

insert into public.usuario_permissoes (user_id, modulo)
select p.id, 'agendamento_marcacao_automacao'
from public.profiles p
where p.ativo = true
  and lower(replace(replace(coalesce(p.setor, ''), 'ã', 'a'), 'ç', 'c')) = 'marcacao'
on conflict (user_id, modulo) do nothing;

insert into public.usuario_permissoes (user_id, modulo)
select p.id, 'agendamento_marcacao_automacao'
from public.profiles p
where p.ativo = true
  and exists (select 1 from public.user_roles ur where ur.user_id = p.id and ur.role in ('admin_master'::public.app_role, 'administrador'::public.app_role))
on conflict (user_id, modulo) do nothing;
