-- Monitoramento: tempo de resposta, método e histórico imutável de verificações.
alter table public.controle_ip
  add column if not exists tempo_resposta_ms integer,
  add column if not exists metodo_monitoramento text not null default 'http_browser',
  add column if not exists erro_monitoramento text,
  add column if not exists historico_status jsonb not null default '[]'::jsonb;

create table if not exists public.controle_ip_historico_status (
  id bigint generated by default as identity primary key,
  controle_ip_id bigint not null references public.controle_ip(id) on delete cascade,
  status_online text not null check (status_online in ('online', 'offline')),
  tempo_resposta_ms integer,
  metodo_monitoramento text not null default 'http_browser',
  erro text,
  verificado_por uuid references auth.users(id),
  verificado_em timestamptz not null default now()
);

create index if not exists controle_ip_historico_status_ip_idx
  on public.controle_ip_historico_status(controle_ip_id, verificado_em desc);

grant select on public.controle_ip_historico_status to authenticated;
grant all on public.controle_ip_historico_status to service_role;
alter table public.controle_ip_historico_status enable row level security;
drop policy if exists controle_ip_historico_select on public.controle_ip_historico_status;
create policy controle_ip_historico_select on public.controle_ip_historico_status
  for select to authenticated
  using (public.tem_modulo(auth.uid(), 'controle_ip'));

create or replace function public.registrar_historico_controle_ip()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  entrada jsonb;
begin
  if new.status_online in ('online', 'offline')
    and (tg_op = 'INSERT' or new.status_online is distinct from old.status_online or new.ultima_verificacao is distinct from old.ultima_verificacao) then
    insert into public.controle_ip_historico_status (
      controle_ip_id, status_online, tempo_resposta_ms, metodo_monitoramento,
      erro, verificado_por, verificado_em
    ) values (
      new.id, new.status_online, new.tempo_resposta_ms,
      coalesce(new.metodo_monitoramento, 'http_browser'), new.erro_monitoramento,
      auth.uid(),
      coalesce(new.ultima_verificacao, now())
    );
    entrada := jsonb_build_object(
      'status_online', new.status_online,
      'tempo_resposta_ms', new.tempo_resposta_ms,
      'metodo_monitoramento', coalesce(new.metodo_monitoramento, 'http_browser'),
      'erro', new.erro_monitoramento,
      'verificado_em', coalesce(new.ultima_verificacao, now()),
      'verificado_por', auth.uid()
    );
    new.historico_status := coalesce(old.historico_status, '[]'::jsonb) || jsonb_build_array(entrada);
  end if;
  return new;
end;
$$;

drop trigger if exists trg_controle_ip_historico_status on public.controle_ip;
create trigger trg_controle_ip_historico_status
before insert or update of status_online, ultima_verificacao, tempo_resposta_ms, metodo_monitoramento
on public.controle_ip for each row execute function public.registrar_historico_controle_ip();
revoke execute on function public.registrar_historico_controle_ip() from public, anon, authenticated;
