-- Ficha técnica de aparelhos de ultrassom e equipamentos médicos.
create table if not exists public.equipamentos_us (
  id bigint generated by default as identity primary key,
  nome text not null,
  localizacao text not null,
  modelo text not null,
  fabricante text,
  ano_fabricacao integer,
  patrimonio text not null,
  serial text not null,
  numero_anvisa text,
  versao_software text,
  ip text,
  porta text,
  gateway text,
  mascara text,
  dns text,
  mac text,
  aetitle text,
  worklist text,
  storage_scp text,
  storage_scu text,
  servidor_dicom text,
  porta_dicom text,
  observacoes_dicom text,
  usuario text,
  senha_cifrada text,
  senha_cadastrada boolean not null default false,
  ultima_manutencao date,
  proxima_manutencao date,
  empresa_responsavel text,
  contato_tecnico text,
  telefone_tecnico text,
  contrato_vigente boolean not null default false,
  alerta_manutencao boolean not null default true,
  dias_alerta_manutencao integer not null default 30 check (dias_alerta_manutencao between 1 and 365),
  observacoes text,
  status text not null default 'operacional' check (status in ('operacional','atencao','manutencao_vencida','inativo')),
  criado_por uuid not null references auth.users(id) on delete set null default auth.uid(),
  criado_em timestamptz not null default now(),
  atualizado_por uuid references auth.users(id) on delete set null,
  atualizado_em timestamptz not null default now()
);

alter table public.equipamentos_us
  add column if not exists senha_cadastrada boolean not null default false;

create unique index if not exists equipamentos_us_patrimonio_idx on public.equipamentos_us (lower(patrimonio));
create index if not exists equipamentos_us_nome_idx on public.equipamentos_us (lower(nome));
create index if not exists equipamentos_us_serial_idx on public.equipamentos_us (lower(serial));
create index if not exists equipamentos_us_ip_idx on public.equipamentos_us (ip);
create index if not exists equipamentos_us_manutencao_idx on public.equipamentos_us (proxima_manutencao);
drop trigger if exists trg_equipamentos_us_touch on public.equipamentos_us;
create trigger trg_equipamentos_us_touch before update on public.equipamentos_us for each row execute function public.touch_updated_at();

create table if not exists public.equipamentos_us_historico (
  id bigint generated by default as identity primary key,
  equipamento_id bigint not null references public.equipamentos_us(id) on delete cascade,
  operacao text not null,
  campo text,
  dados_anteriores jsonb,
  dados_novos jsonb,
  criado_por uuid references auth.users(id) on delete set null,
  criado_em timestamptz not null default now()
);
create index if not exists equipamentos_us_hist_equip_idx on public.equipamentos_us_historico (equipamento_id, criado_em desc);

create table if not exists public.equipamentos_us_documentos (
  id bigint generated by default as identity primary key,
  equipamento_id bigint not null references public.equipamentos_us(id) on delete cascade,
  nome_arquivo text not null,
  caminho_storage text not null,
  tipo text,
  tamanho bigint,
  criado_por uuid references auth.users(id) on delete set null,
  criado_em timestamptz not null default now()
);

-- RLS por permissão do módulo; senhas nunca são retornadas por listas da aplicação.
grant select, insert, update, delete on public.equipamentos_us to authenticated;
grant select, insert on public.equipamentos_us_historico to authenticated;
grant select, insert, delete on public.equipamentos_us_documentos to authenticated;
grant all on public.equipamentos_us, public.equipamentos_us_historico, public.equipamentos_us_documentos to service_role;

do $$ begin
  alter table public.equipamentos_us enable row level security;
  alter table public.equipamentos_us_historico enable row level security;
  alter table public.equipamentos_us_documentos enable row level security;
exception when others then null; end $$;

drop policy if exists "equipamentos_us_select" on public.equipamentos_us;
drop policy if exists "equipamentos_us_insert" on public.equipamentos_us;
drop policy if exists "equipamentos_us_update" on public.equipamentos_us;
drop policy if exists "equipamentos_us_delete" on public.equipamentos_us;
create policy "equipamentos_us_select" on public.equipamentos_us for select to authenticated using (public.is_admin(auth.uid()) or public.tem_modulo(auth.uid(), 'equipamentos_us'));
create policy "equipamentos_us_insert" on public.equipamentos_us for insert to authenticated with check (public.pode_editar(auth.uid(), 'equipamentos_us_adicionar'));
create policy "equipamentos_us_update" on public.equipamentos_us for update to authenticated using (public.is_admin(auth.uid()) or public.pode_editar(auth.uid(), 'equipamentos_us_editar')) with check (public.is_admin(auth.uid()) or public.pode_editar(auth.uid(), 'equipamentos_us_editar'));
create policy "equipamentos_us_delete" on public.equipamentos_us for delete to authenticated using (public.is_admin(auth.uid()) or public.pode_editar(auth.uid(), 'equipamentos_us_excluir'));

drop policy if exists "equipamentos_us_hist_select" on public.equipamentos_us_historico;
drop policy if exists "equipamentos_us_hist_insert" on public.equipamentos_us_historico;
create policy "equipamentos_us_hist_select" on public.equipamentos_us_historico for select to authenticated using (public.is_admin(auth.uid()) or public.tem_modulo(auth.uid(), 'equipamentos_us'));
create policy "equipamentos_us_hist_insert" on public.equipamentos_us_historico for insert to authenticated with check (public.is_admin(auth.uid()) or public.tem_modulo(auth.uid(), 'equipamentos_us'));

drop policy if exists "equipamentos_us_docs_select" on public.equipamentos_us_documentos;
create policy "equipamentos_us_docs_select" on public.equipamentos_us_documentos for select to authenticated using (public.is_admin(auth.uid()) or public.tem_modulo(auth.uid(), 'equipamentos_us'));
