-- Permite que administradores personalizem os textos e botões do menu principal.
create table if not exists public.menu_itens (
  id bigint generated by default as identity primary key,
  chave text not null unique,
  grupo text not null default 'Geral',
  grupo_ordem integer not null default 100,
  rotulo varchar(120) not null,
  destino varchar(255) not null,
  icone varchar(40) not null default 'LayoutDashboard',
  modulo varchar(80),
  ordem integer not null default 100,
  ativo boolean not null default true,
  somente_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint menu_itens_rotulo_nao_vazio check (btrim(rotulo) <> ''),
  constraint menu_itens_destino_nao_vazio check (btrim(destino) <> ''),
  constraint menu_itens_ordem_valida check (ordem >= 0 and grupo_ordem >= 0)
);

comment on table public.menu_itens is
  'Itens do menu principal que podem ser personalizados por administradores.';

create index if not exists menu_itens_visiveis_idx
  on public.menu_itens (ativo, grupo_ordem, ordem);

insert into public.menu_itens
  (chave, grupo, grupo_ordem, rotulo, destino, icone, modulo, ordem, somente_admin)
values
  ('painel', 'Visão geral', 10, 'Painel', '/dashboard', 'LayoutDashboard', null, 10, false),
  ('ramais', 'Visão geral', 10, 'Ramais', '/ramais', 'Phone', null, 20, false),
  ('escala', 'Salas', 20, 'Escala semanal', '/escala', 'CalendarDays', 'escalas', 10, false),
  ('salas', 'Salas', 20, 'Salas de exame', '/salas', 'DoorOpen', 'salas', 20, false),
  ('colaboradoras', 'Salas', 20, 'Colaboradoras', '/colaboradoras', 'Users', 'colaboradoras', 30, false),
  ('medicos', 'Salas', 20, 'Médicos', '/medicos', 'Stethoscope', 'medicos', 40, false),
  ('ausencias', 'Salas', 20, 'Ausências', '/dashboard', 'CalendarOff', 'ausencias', 50, false),
  ('itens', 'Suprimentos', 30, 'Itens e materiais', '/itens', 'Boxes', 'itens', 10, false),
  ('estoque', 'Suprimentos', 30, 'Estoque', '/estoque', 'Package', 'estoque', 20, false),
  ('fornecedores', 'Suprimentos', 30, 'Fornecedores', '/fornecedores', 'ClipboardList', 'fornecedores', 30, false),
  ('solicitacoes', 'Suprimentos', 30, 'Solicitações', '/solicitacoes', 'ClipboardList', 'solicitacoes', 40, false),
  ('enfermagem', 'Enfermagem', 40, 'Atendimentos', '/enfermagem', 'HeartPulse', 'enfermagem', 10, false),
  ('escala-enfermagem', 'Enfermagem', 40, 'Escala semanal', '/escala-enfermagem', 'CalendarDays', 'escala_enfermagem_visualizar', 20, false),
  ('salas-enfermagem', 'Enfermagem', 40, 'Salas de exames', '/salas-enfermagem', 'DoorOpen', 'enfermagem', 30, false),
  ('colaboradoras-enfermagem', 'Enfermagem', 40, 'Colaboradoras', '/colaboradoras-enfermagem', 'Users', 'enfermagem', 40, false),
  ('medicos-enfermagem', 'Enfermagem', 40, 'Médicos', '/medicos-enfermagem', 'Stethoscope', 'enfermagem', 50, false),
  ('pacientes', 'Enfermagem', 40, 'Pacientes', '/pacientes', 'Users', 'enfermagem', 60, false),
  ('sondas', 'Enfermagem', 40, 'Sondas', '/sondas', 'Waves', 'sondas', 70, false),
  ('notas', 'Apoio', 50, 'Notas', '/notas', 'StickyNote', 'notas', 10, false),
  ('lembretes', 'Apoio', 50, 'Lembretes', '/lembretes', 'BellRing', 'lembretes', 20, false),
  ('equipamentos-us', 'Apoio', 50, 'Aparelhos de US / Equipamentos', '/equipamentos-us', 'MonitorCog', 'equipamentos_us', 30, false),
  ('agenda-marcacao', 'Apoio', 50, 'Minha Agenda', '/agenda-marcacao', 'CalendarHeart', 'agenda_marcacao', 40, false),
  ('relatorios', 'Apoio', 50, 'Relatórios', '/relatorios', 'BarChart3', 'relatorios', 50, false),
  ('senhas', 'Apoio', 50, 'Senhas', '/senhas', 'KeyRound', 'senhas', 60, false),
  ('controle-ip', 'Rede', 60, 'Controle de IP', '/controle-ip', 'Network', 'controle_ip', 10, false),
  ('lixeira', 'Sistema', 70, 'Lixeira', '/lixeira', 'Trash2', 'lixeira', 10, false)
on conflict (chave) do nothing;

grant select, insert, update, delete on public.menu_itens to authenticated;
alter table public.menu_itens enable row level security;

drop policy if exists menu_itens_select on public.menu_itens;
create policy menu_itens_select
  on public.menu_itens for select to authenticated
  using (public.is_ativo(auth.uid()));

drop policy if exists menu_itens_admin on public.menu_itens;
create policy menu_itens_admin
  on public.menu_itens for all to authenticated
  using (public.is_admin(auth.uid()))
  with check (public.is_admin(auth.uid()));
