-- Escalas independentes por setor: Salas, Enfermagem e Marcação.
-- A nova tela da Marcação possui tabela própria e permissões independentes.

create table if not exists public.escalas_marcacao (
  id bigint generated by default as identity primary key,
  data date not null,
  periodo text,
  responsaveis text,
  observacoes text,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);
create index if not exists escalas_marcacao_data_idx on public.escalas_marcacao (data);
drop trigger if exists trg_escalas_marcacao_touch on public.escalas_marcacao;
create trigger trg_escalas_marcacao_touch before update on public.escalas_marcacao
for each row execute function public.touch_updated_at();
grant select, insert, update, delete on public.escalas_marcacao to authenticated;
grant all on public.escalas_marcacao to service_role;
grant usage, select on sequence public.escalas_marcacao_id_seq to authenticated;
alter table public.escalas_marcacao enable row level security;
drop policy if exists escalas_marcacao_select on public.escalas_marcacao;
drop policy if exists escalas_marcacao_insert on public.escalas_marcacao;
drop policy if exists escalas_marcacao_update on public.escalas_marcacao;
drop policy if exists escalas_marcacao_delete on public.escalas_marcacao;
create policy escalas_marcacao_select on public.escalas_marcacao for select to authenticated
using (public.tem_modulo(auth.uid(), 'escala_marcacao_visualizar') or public.tem_modulo(auth.uid(), 'escala_marcacao_editar'));
create policy escalas_marcacao_insert on public.escalas_marcacao for insert to authenticated
with check (public.pode_editar(auth.uid(), 'escala_marcacao_editar'));
create policy escalas_marcacao_update on public.escalas_marcacao for update to authenticated
using (public.pode_editar(auth.uid(), 'escala_marcacao_editar'))
with check (public.pode_editar(auth.uid(), 'escala_marcacao_editar'));
create policy escalas_marcacao_delete on public.escalas_marcacao for delete to authenticated
using (public.pode_editar(auth.uid(), 'escala_marcacao_editar'));

-- Catálogo de permissões e migração das permissões antigas da escala de Salas.
update public.setores
set permissoes_padrao = array(
  select distinct permissao from unnest(permissoes_padrao || array['escala_salas_visualizar','escala_salas_editar']::text[]) p(permissao)
  order by permissao
), atualizado_em = now()
where papel_padrao in ('admin_master'::public.app_role, 'administrador'::public.app_role);
update public.setores
set permissoes_padrao = array(
  select distinct permissao from unnest(permissoes_padrao || array['escala_marcacao_visualizar','escala_marcacao_editar']::text[]) p(permissao)
  order by permissao
), atualizado_em = now()
where lower(replace(nome, 'ã', 'a')) = 'marcacao' or papel_padrao = 'marcacao'::public.app_role;
insert into public.usuario_permissoes (user_id, modulo)
select distinct up.user_id, 'escala_salas_visualizar'
from public.usuario_permissoes up
where up.modulo in ('escalas', 'escalas_visualizar', 'escalas_editar')
on conflict (user_id, modulo) do nothing;
insert into public.usuario_permissoes (user_id, modulo)
select distinct up.user_id, 'escala_salas_editar'
from public.usuario_permissoes up
where up.modulo in ('escalas', 'escalas_editar')
on conflict (user_id, modulo) do nothing;
insert into public.usuario_permissoes (user_id, modulo)
select p.id, permissao
from public.profiles p
join public.setores s on s.id = p.setor_id
cross join unnest(array['escala_marcacao_visualizar','escala_marcacao_editar']::text[]) permissao
where lower(replace(coalesce(s.nome, ''), 'ã', 'a')) = 'marcacao' or s.papel_padrao = 'marcacao'::public.app_role
on conflict (user_id, modulo) do nothing;

-- Acesso da escala de Salas passa a depender das permissões específicas.
alter table public.escalas enable row level security;
drop policy if exists escalas_select on public.escalas;
drop policy if exists escalas_insert on public.escalas;
drop policy if exists escalas_update on public.escalas;
drop policy if exists escalas_delete on public.escalas;
drop policy if exists escalas_setor_select on public.escalas;
drop policy if exists escalas_setor_insert on public.escalas;
drop policy if exists escalas_setor_update on public.escalas;
drop policy if exists escalas_setor_delete on public.escalas;
create policy escalas_setor_select on public.escalas for select to authenticated
using (public.tem_modulo(auth.uid(), 'escala_salas_visualizar') or public.tem_modulo(auth.uid(), 'escala_salas_editar'));
create policy escalas_setor_insert on public.escalas for insert to authenticated
with check (public.pode_editar(auth.uid(), 'escala_salas_editar'));
create policy escalas_setor_update on public.escalas for update to authenticated
using (public.pode_editar(auth.uid(), 'escala_salas_editar')) with check (public.pode_editar(auth.uid(), 'escala_salas_editar'));
create policy escalas_setor_delete on public.escalas for delete to authenticated
using (public.pode_editar(auth.uid(), 'escala_salas_editar'));

insert into public.menu_itens (chave, grupo, grupo_ordem, rotulo, destino, icone, modulo, ordem, somente_admin)
values ('escala-marcacao', 'Marcação', 50, 'Escala semanal', '/escala-marcacao', 'CalendarDays', 'escala_marcacao_visualizar', 35, false)
on conflict (chave) do update set modulo = excluded.modulo, rotulo = excluded.rotulo, destino = excluded.destino;

-- Chat da Marcação com a supervisora Geisiane.
alter table public.chat_salas_mensagens drop constraint if exists chat_salas_mensagens_canal_check;
alter table public.chat_salas_mensagens add constraint chat_salas_mensagens_canal_check
check (canal in ('salas', 'enfermagem', 'marcacao'));
create or replace function public.pode_chat_marcacao(_user_id uuid)
returns boolean language sql stable security definer set search_path = public, auth as $$
  select public.is_ativo(_user_id) and (
    public.is_admin(_user_id)
    or exists (select 1 from public.usuario_permissoes where user_id = _user_id and modulo = 'chat_marcacao')
    or exists (select 1 from auth.users where id = _user_id and lower(email) = 'marcacao@clinicaceu.com.br')
  )
$$;
create or replace function public.chat_marcacao_eh_supervisora(_user_id uuid)
returns boolean language sql stable security definer set search_path = public, auth as $$
  select public.pode_chat_marcacao(_user_id) and exists (
    select 1 from auth.users u join public.profiles p on p.id = u.id
    where u.id = _user_id and (lower(u.email) = 'marcacao@clinicaceu.com.br' or lower(trim(p.nome)) = 'geisiane taise gomes moraes')
  )
$$;
create or replace function public.obter_chat_marcacao_supervisora()
returns table (id uuid, nome text, setor text, ativo boolean)
language sql stable security definer set search_path = public, auth as $$
  select p.id, p.nome, p.setor, p.ativo
  from public.profiles p join auth.users u on u.id = p.id
  where p.ativo = true and (lower(u.email) = 'marcacao@clinicaceu.com.br' or lower(trim(p.nome)) = 'geisiane taise gomes moraes')
  order by (lower(u.email) = 'marcacao@clinicaceu.com.br') desc
  limit 1
$$;
grant execute on function public.pode_chat_marcacao(uuid) to authenticated;
grant execute on function public.chat_marcacao_eh_supervisora(uuid) to authenticated;
grant execute on function public.obter_chat_marcacao_supervisora() to authenticated;
drop policy if exists escalas_enfermagem_select on public.escalas_enfermagem;
drop policy if exists escalas_enfermagem_insert on public.escalas_enfermagem;
drop policy if exists escalas_enfermagem_update on public.escalas_enfermagem;
drop policy if exists escalas_enfermagem_delete on public.escalas_enfermagem;
create policy escalas_enfermagem_select on public.escalas_enfermagem for select to authenticated
using (public.tem_modulo(auth.uid(), 'escala_enfermagem_visualizar') or public.tem_modulo(auth.uid(), 'escala_enfermagem_editar'));
create policy escalas_enfermagem_insert on public.escalas_enfermagem for insert to authenticated
with check (public.pode_editar(auth.uid(), 'escala_enfermagem_editar'));
create policy escalas_enfermagem_update on public.escalas_enfermagem for update to authenticated
using (public.pode_editar(auth.uid(), 'escala_enfermagem_editar')) with check (public.pode_editar(auth.uid(), 'escala_enfermagem_editar'));
create policy escalas_enfermagem_delete on public.escalas_enfermagem for delete to authenticated
using (public.pode_editar(auth.uid(), 'escala_enfermagem_editar'));
create policy chat_marcacao_select on public.chat_salas_mensagens for select to authenticated
using (canal = 'marcacao' and public.pode_chat_marcacao(auth.uid()) and (remetente_id = auth.uid() or destinatario_id = auth.uid() or public.chat_marcacao_eh_supervisora(auth.uid())));
create policy chat_marcacao_insert on public.chat_salas_mensagens for insert to authenticated
with check (canal = 'marcacao' and public.pode_chat_marcacao(auth.uid()) and remetente_id = auth.uid() and public.pode_chat_marcacao(destinatario_id) and (public.chat_marcacao_eh_supervisora(auth.uid()) or public.chat_marcacao_eh_supervisora(destinatario_id)));
create policy chat_marcacao_update on public.chat_salas_mensagens for update to authenticated
using (canal = 'marcacao' and public.pode_chat_marcacao(auth.uid()) and (destinatario_id = auth.uid() or public.chat_marcacao_eh_supervisora(auth.uid())))
with check (canal = 'marcacao' and public.pode_chat_marcacao(auth.uid()) and (destinatario_id = auth.uid() or public.chat_marcacao_eh_supervisora(auth.uid())));

drop policy if exists profiles_chat_marcacao_select on public.profiles;
create policy profiles_chat_marcacao_select on public.profiles for select to authenticated
using (public.pode_chat_marcacao(auth.uid()) and (lower(replace(coalesce(setor, ''), 'ã', 'a')) = 'marcacao' or public.chat_marcacao_eh_supervisora(id)));
insert into public.menu_itens (chave, grupo, grupo_ordem, rotulo, destino, icone, modulo, ordem, somente_admin)
values ('chat-marcacao', 'Marcação', 50, 'Falar com Geisi', '/chat-marcacao', 'MessageCircle', 'chat_marcacao', 36, false)
on conflict (chave) do update set modulo = excluded.modulo, rotulo = excluded.rotulo, destino = excluded.destino;
insert into public.usuario_permissoes (user_id, modulo)
select p.id, 'chat_marcacao'
from public.profiles p
where lower(replace(coalesce(p.setor, ''), 'ã', 'a')) = 'marcacao' and p.ativo = true
on conflict (user_id, modulo) do nothing;
insert into public.usuario_permissoes (user_id, modulo)
select u.id, 'chat_marcacao'
from auth.users u
where lower(u.email) = 'marcacao@clinicaceu.com.br'
on conflict (user_id, modulo) do nothing;

-- Somente a Marilia Frontzek é retornada como coordenadora das Salas.
create or replace function public.obter_chat_salas_coordenadora()
returns table (id uuid, nome text, setor text, ativo boolean)
language sql stable security definer set search_path = public, auth as $$
  select p.id, p.nome, p.setor, p.ativo
  from public.profiles p join auth.users u on u.id = p.id
  where p.ativo = true
    and (lower(trim(p.nome)) = 'marilia frontzek' or lower(u.email) in ('supervisaosalas@clinicaceu.com.br', 'supervisaosalas@clinicacue.com.br'))
  order by (lower(trim(p.nome)) = 'marilia frontzek') desc,
           (lower(u.email) = 'supervisaosalas@clinicacue.com.br') desc
  limit 1
$$;
grant execute on function public.obter_chat_salas_coordenadora() to authenticated;
