-- Inventário técnico de sondas/transdutores, compatível com o controle operacional já existente.
create table if not exists public.sondas (
  id bigint generated by default as identity primary key,
  nome text not null,
  modelo text not null,
  fabricante text,
  tipo text not null,
  serial text not null,
  patrimonio text,
  ano_fabricacao integer,
  frequencia text,
  numero_anvisa text,
  localizacao text not null,
  sala text,
  setor text,
  data_aquisicao date,
  garantia text,
  status text not null default 'em_uso' check (status in ('em_uso','reserva','manutencao','inativa','baixada')),
  ultima_manutencao date,
  proxima_manutencao date,
  empresa_responsavel text,
  contato_tecnico text,
  telefone_tecnico text,
  observacoes_manutencao text,
  observacoes text,
  criado_por uuid not null references auth.users(id) on delete set null default auth.uid(),
  criado_em timestamptz not null default now(),
  atualizado_por uuid references auth.users(id) on delete set null,
  atualizado_em timestamptz not null default now()
);

create unique index if not exists sondas_serial_idx on public.sondas(lower(serial));
create index if not exists sondas_status_idx on public.sondas(status);
create index if not exists sondas_manutencao_idx on public.sondas(proxima_manutencao);

create table if not exists public.sondas_equipamentos (
  id bigint generated by default as identity primary key,
  sonda_id bigint not null references public.sondas(id) on delete cascade,
  equipamento_id bigint not null references public.equipamentos_us(id) on delete cascade,
  criado_por uuid references auth.users(id) on delete set null default auth.uid(),
  criado_em timestamptz not null default now(),
  unique (sonda_id, equipamento_id)
);

create table if not exists public.sondas_ocorrencias (
  id bigint generated by default as identity primary key,
  sonda_id bigint not null references public.sondas(id) on delete cascade,
  data date not null default current_date,
  tipo text not null,
  descricao text not null,
  anexo_nome text,
  criado_por uuid references auth.users(id) on delete set null default auth.uid(),
  criado_em timestamptz not null default now()
);

create table if not exists public.sondas_documentos (
  id bigint generated by default as identity primary key,
  sonda_id bigint not null references public.sondas(id) on delete cascade,
  nome_arquivo text not null,
  caminho_storage text not null,
  tipo text,
  tamanho bigint,
  criado_por uuid references auth.users(id) on delete set null default auth.uid(),
  criado_em timestamptz not null default now()
);

-- Reexecução segura em bancos que já tenham a tabela.
alter table public.sondas add column if not exists observacoes_manutencao text;
alter table public.sondas add column if not exists garantia text;
alter table public.sondas add column if not exists atualizado_por uuid references auth.users(id) on delete set null;
alter table public.sondas add column if not exists atualizado_em timestamptz not null default now();
drop trigger if exists trg_sondas_touch on public.sondas;
create trigger trg_sondas_touch before update on public.sondas for each row execute function public.touch_updated_at();

grant select, insert, update, delete on public.sondas, public.sondas_equipamentos, public.sondas_ocorrencias, public.sondas_documentos to authenticated;
grant all on public.sondas, public.sondas_equipamentos, public.sondas_ocorrencias, public.sondas_documentos to service_role;

alter table public.sondas enable row level security;
alter table public.sondas_equipamentos enable row level security;
alter table public.sondas_ocorrencias enable row level security;
alter table public.sondas_documentos enable row level security;

drop policy if exists sondas_select on public.sondas;
drop policy if exists sondas_insert on public.sondas;
drop policy if exists sondas_update on public.sondas;
drop policy if exists sondas_delete on public.sondas;
create policy sondas_select on public.sondas for select to authenticated using (public.is_admin(auth.uid()) or public.tem_modulo(auth.uid(), 'sondas'));
create policy sondas_insert on public.sondas for insert to authenticated with check (public.is_admin(auth.uid()) or public.pode_editar(auth.uid(), 'sondas_adicionar'));
create policy sondas_update on public.sondas for update to authenticated using (public.is_admin(auth.uid()) or public.pode_editar(auth.uid(), 'sondas_editar')) with check (public.is_admin(auth.uid()) or public.pode_editar(auth.uid(), 'sondas_editar'));
create policy sondas_delete on public.sondas for delete to authenticated using (public.is_admin(auth.uid()) or public.pode_editar(auth.uid(), 'sondas_excluir'));

do $do$
declare t text; begin
  foreach t in array array['sondas_equipamentos','sondas_ocorrencias','sondas_documentos'] loop
    execute format('drop policy if exists %I_select on public.%I', t, t);
    execute format('drop policy if exists %I_write on public.%I', t, t);
    execute format('create policy %I_select on public.%I for select to authenticated using (public.is_admin(auth.uid()) or public.tem_modulo(auth.uid(), ''sondas''))', t, t);
    execute format('create policy %I_write on public.%I for all to authenticated using (public.is_admin(auth.uid()) or public.tem_modulo(auth.uid(), ''sondas_editar'')) with check (public.is_admin(auth.uid()) or public.tem_modulo(auth.uid(), ''sondas_editar''))', t, t);
  end loop;
end $do$;
