create table public.ramais (
  id bigint generated by default as identity primary key,
  numero text,
  setor text,
  responsavel text,
  localizacao text,
  categoria text,
  situacao text not null default 'Em uso',
  observacoes text,
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index ramais_numero_unico on public.ramais (numero) where numero is not null;
create index ramais_setor_idx on public.ramais (setor);
create index ramais_situacao_idx on public.ramais (situacao);

grant select, insert, update, delete on public.ramais to authenticated;
grant all on public.ramais to service_role;

alter table public.ramais enable row level security;

create policy "ramais_select" on public.ramais for select to authenticated
  using (public.is_ativo(auth.uid()));
create policy "ramais_insert" on public.ramais for insert to authenticated
  with check (public.pode_editar(auth.uid(), 'ramais'));
create policy "ramais_update" on public.ramais for update to authenticated
  using (public.pode_editar(auth.uid(), 'ramais'))
  with check (public.pode_editar(auth.uid(), 'ramais'));
create policy "ramais_delete" on public.ramais for delete to authenticated
  using (public.pode_editar(auth.uid(), 'ramais'));

create trigger trg_ramais_touch before update on public.ramais
  for each row execute function public.touch_updated_at();

create or replace function public.audit_ramais()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_nome text;
begin
  select nome into v_nome from public.profiles where id = auth.uid();
  insert into public.audit_logs (user_id, usuario_nome, tabela, operacao, registro_id, dados_anteriores, dados_novos)
  values (
    auth.uid(),
    coalesce(v_nome, 'sistema'),
    'ramais',
    tg_op,
    coalesce(new.id, old.id)::text,
    case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) else null end,
    case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) else null end
  );
  return coalesce(new, old);
end;
$$;

create trigger trg_ramais_audit
  after insert or update or delete on public.ramais
  for each row execute function public.audit_ramais();