-- Presença online e mensagens diretas com o Administrador Master.
create table if not exists public.usuario_presenca (
  user_id uuid primary key references auth.users(id) on delete cascade,
  ultimo_acesso timestamptz not null default now()
);

create index if not exists usuario_presenca_ultimo_acesso_idx
  on public.usuario_presenca (ultimo_acesso desc);

grant select, insert, update on public.usuario_presenca to authenticated;
alter table public.usuario_presenca enable row level security;

drop policy if exists usuario_presenca_select on public.usuario_presenca;
create policy usuario_presenca_select on public.usuario_presenca
for select to authenticated using (public.is_ativo(auth.uid()));

drop policy if exists usuario_presenca_write on public.usuario_presenca;
create policy usuario_presenca_write on public.usuario_presenca
for insert to authenticated with check (user_id = auth.uid());

drop policy if exists usuario_presenca_update on public.usuario_presenca;
create policy usuario_presenca_update on public.usuario_presenca
for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

create or replace function public.marcar_usuario_online()
returns void language sql security definer set search_path = public as $$
  insert into public.usuario_presenca (user_id, ultimo_acesso)
  values (auth.uid(), now())
  on conflict (user_id) do update set ultimo_acesso = now();
$$;
grant execute on function public.marcar_usuario_online() to authenticated;

create table if not exists public.chat_admin_mensagens (
  id bigint generated by default as identity primary key,
  remetente_id uuid not null references auth.users(id) on delete cascade,
  destinatario_id uuid not null references auth.users(id) on delete cascade,
  mensagem text,
  criado_em timestamptz not null default now(),
  lida_em timestamptz,
  constraint chat_admin_conteudo_check check (nullif(btrim(mensagem), '') is not null),
  constraint chat_admin_remetente_diferente check (remetente_id <> destinatario_id)
);

create index if not exists chat_admin_conversa_idx
  on public.chat_admin_mensagens (remetente_id, destinatario_id, criado_em);

grant select, insert, update on public.chat_admin_mensagens to authenticated;
alter table public.chat_admin_mensagens enable row level security;

drop policy if exists chat_admin_select on public.chat_admin_mensagens;
create policy chat_admin_select on public.chat_admin_mensagens for select to authenticated using (
  public.is_master(auth.uid()) or remetente_id = auth.uid() or destinatario_id = auth.uid()
);

drop policy if exists chat_admin_insert on public.chat_admin_mensagens;
create policy chat_admin_insert on public.chat_admin_mensagens for insert to authenticated with check (
  remetente_id = auth.uid()
  and (
    public.is_master(auth.uid())
    or public.is_master(destinatario_id)
  )
  and public.is_ativo(destinatario_id)
);

drop policy if exists chat_admin_update on public.chat_admin_mensagens;
create policy chat_admin_update on public.chat_admin_mensagens for update to authenticated using (
  destinatario_id = auth.uid() or public.is_master(auth.uid())
) with check (
  destinatario_id = auth.uid() or public.is_master(auth.uid())
);

-- O Administrador Master pode auditar os históricos dos canais restritos.
drop policy if exists chat_salas_mensagens_select on public.chat_salas_mensagens;
create policy chat_salas_mensagens_select on public.chat_salas_mensagens for select to authenticated using (
  public.is_master(auth.uid())
  or (canal = 'salas' and public.pode_chat_salas(auth.uid()) and (remetente_id = auth.uid() or destinatario_id = auth.uid() or public.chat_salas_eh_coordenadora(auth.uid())))
  or (canal = 'enfermagem' and public.pode_chat_enfermagem(auth.uid()) and (remetente_id = auth.uid() or destinatario_id = auth.uid() or public.chat_enfermagem_eh_coordenadora(auth.uid())))
);

drop policy if exists chat_salas_mensagens_update on public.chat_salas_mensagens;
create policy chat_salas_mensagens_update on public.chat_salas_mensagens for update to authenticated using (
  public.is_master(auth.uid())
  or (canal = 'salas' and public.pode_chat_salas(auth.uid()) and (destinatario_id = auth.uid() or public.chat_salas_eh_coordenadora(auth.uid())))
  or (canal = 'enfermagem' and public.pode_chat_enfermagem(auth.uid()) and (destinatario_id = auth.uid() or public.chat_enfermagem_eh_coordenadora(auth.uid())))
) with check (
  public.is_master(auth.uid())
  or (canal = 'salas' and public.pode_chat_salas(auth.uid()) and (destinatario_id = auth.uid() or public.chat_salas_eh_coordenadora(auth.uid())))
  or (canal = 'enfermagem' and public.pode_chat_enfermagem(auth.uid()) and (destinatario_id = auth.uid() or public.chat_enfermagem_eh_coordenadora(auth.uid())))
);

create or replace function public.obter_administradores_master()
returns table (id uuid, nome text, setor text, ativo boolean)
language sql stable security definer set search_path = public as $$
  select p.id, p.nome, p.setor, p.ativo
  from public.profiles p
  join public.user_roles ur on ur.user_id = p.id
  where ur.role = 'admin_master' and p.ativo = true
  order by p.nome;
$$;
grant execute on function public.obter_administradores_master() to authenticated;

insert into public.menu_itens
  (chave, grupo, grupo_ordem, rotulo, destino, icone, modulo, ordem, somente_admin)
values
  ('chat-admin', 'Apoio', 50, 'Mensagens', '/chat-admin', 'MessageCircle', null, 5, false)
on conflict (chave) do nothing;

insert into public.menu_itens
  (chave, grupo, grupo_ordem, rotulo, destino, icone, modulo, ordem, somente_admin)
values
  ('auditoria-mensagens', 'Sistema', 70, 'Auditoria de mensagens', '/auditoria-mensagens', 'ClipboardList', null, 20, true)
on conflict (chave) do nothing;
