-- Cronograma recorrente de atividades semanais do setor de Enfermagem.
-- dia_semana segue ISO: 1=segunda-feira ... 5=sexta-feira.
create table if not exists public.atividades_enfermagem (
  id bigint generated by default as identity primary key,
  dia_semana smallint not null check (dia_semana between 1 and 5),
  titulo text not null check (length(btrim(titulo)) between 1 and 180),
  horario time,
  descricao text check (descricao is null or length(descricao) <= 2000),
  colaboradora_id bigint references public.colaboradoras(id) on delete set null,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);
create index if not exists atividades_enfermagem_dia_horario_idx
  on public.atividades_enfermagem (dia_semana, horario, titulo);
create index if not exists atividades_enfermagem_colaboradora_idx
  on public.atividades_enfermagem (colaboradora_id);

drop trigger if exists trg_atividades_enfermagem_touch on public.atividades_enfermagem;
create trigger trg_atividades_enfermagem_touch before update on public.atividades_enfermagem
for each row execute function public.touch_updated_at();

grant select, insert, update, delete on public.atividades_enfermagem to authenticated;
grant all on public.atividades_enfermagem to service_role;
alter table public.atividades_enfermagem enable row level security;
drop policy if exists atividades_enfermagem_select on public.atividades_enfermagem;
drop policy if exists atividades_enfermagem_insert on public.atividades_enfermagem;
drop policy if exists atividades_enfermagem_update on public.atividades_enfermagem;
drop policy if exists atividades_enfermagem_delete on public.atividades_enfermagem;
create policy atividades_enfermagem_select on public.atividades_enfermagem for select to authenticated
using (public.is_admin(auth.uid()) or public.tem_modulo(auth.uid(), 'enfermagem'));
create policy atividades_enfermagem_insert on public.atividades_enfermagem for insert to authenticated
with check (
  (public.is_admin(auth.uid()) or public.pode_editar(auth.uid(), 'enfermagem'))
  and (colaboradora_id is null or exists (
    select 1 from public.colaboradoras c
    where c.id = atividades_enfermagem.colaboradora_id and c.setor = 'enfermagem'
  ))
);
create policy atividades_enfermagem_update on public.atividades_enfermagem for update to authenticated
using (public.is_admin(auth.uid()) or public.pode_editar(auth.uid(), 'enfermagem'))
with check (
  (public.is_admin(auth.uid()) or public.pode_editar(auth.uid(), 'enfermagem'))
  and (colaboradora_id is null or exists (
    select 1 from public.colaboradoras c
    where c.id = atividades_enfermagem.colaboradora_id and c.setor = 'enfermagem'
  ))
);
create policy atividades_enfermagem_delete on public.atividades_enfermagem for delete to authenticated
using (public.is_admin(auth.uid()) or public.pode_editar(auth.uid(), 'enfermagem'));

-- Registra o atalho no menu persistente, usado quando a configuração do menu já existe.
insert into public.menu_itens (chave, grupo, grupo_ordem, rotulo, destino, icone, modulo, ordem, somente_admin)
values ('atividades-enfermagem', 'Enfermagem', 40, 'Atividades', '/atividades-enfermagem', 'CalendarDays', 'enfermagem', 25, false)
on conflict (chave) do update set
  grupo = excluded.grupo,
  grupo_ordem = excluded.grupo_ordem,
  rotulo = excluded.rotulo,
  destino = excluded.destino,
  icone = excluded.icone,
  modulo = excluded.modulo,
  ordem = excluded.ordem,
  somente_admin = excluded.somente_admin,
  ativo = true;
